/* A private, chapter-based reading room stored on each character record. */
(()=>{
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const color=value=>/^#[0-9a-f]{6}$/i.test(value||'')?value:'#765a86';
  const luminance=value=>{const channels=[1,3,5].map(index=>parseInt(value.slice(index,index+2),16)/255);return channels.map(channel=>channel<=.04045?channel/12.92:((channel+.055)/1.055)**2.4).reduce((sum,channel,index)=>sum+channel*[.2126,.7152,.0722][index],0);};
  const getChar=()=>characters.find(char=>String(char.id)===String(activeCharId));
  const getBook=char=>char?.archiveBook||{title:`${char?.name||'人物'}記事`,description:'',chapters:[]};
  const chapters=char=>Array.isArray(getBook(char).chapters)?getBook(char).chapters:[];
  let activeCharId='',editing=false,editorSnapshot='',readerChapterId='';

  function palette(char){const a=color(char.themeColor?.primary),b=color(char.themeColor?.secondary||a),ink=(luminance(a)+luminance(b))/2>.38?'#211d27':'#fffaf7';return {a,b,ink,paper:ink==='#211d27'?'#fffaf5':'#211c28',paperInk:ink==='#211d27'?'#28232b':'#faf3ed'};}
  function setPalette(element,char){const theme=palette(char);for(const [key,value] of Object.entries(theme))element.style.setProperty(`--book-${key}`,value);}
  function ensureShell(){if($('characterArchiveModal'))return;const shell=document.createElement('div');shell.id='characterArchiveModal';shell.className='modal-backdrop timeline-books-backdrop character-archive-backdrop';shell.innerHTML=`<div class="timeline-books-shell character-archive-shell"><header class="timeline-books-hero character-archive-hero"><button type="button" class="timeline-books-return" onclick="OCCharacterArchive.close()" aria-label="返回人物卡"><i class="fa-solid fa-arrow-left"></i></button><small>CHARACTER CHRONICLE · PRIVATE READING ROOM</small><div class="character-archive-hero-main"><span id="characterArchivePortrait" class="character-archive-portrait"></span><div><h2 id="characterArchiveName"></h2><p id="characterArchiveSubtitle"></p></div></div><span id="characterArchiveCount" class="character-archive-count"></span><button type="button" class="timeline-books-edit-toggle" id="characterArchiveEditToggle" onclick="OCCharacterArchive.toggleEdit()" aria-pressed="false"><i class="fa-solid fa-pen"></i><span>編輯模式</span></button></header><main id="characterArchiveBody" class="timeline-books-body character-archive-body"></main></div>`;document.body.append(shell);
    const reader=document.createElement('div');reader.id='characterArchiveReader';reader.className='modal-backdrop character-archive-reader';reader.innerHTML='<div class="character-archive-reader-shell"><header><button type="button" onclick="OCCharacterArchive.closeReader()" aria-label="返回章節目錄"><i class="fa-solid fa-arrow-left"></i> 章節目錄</button><small>CHARACTER CHRONICLE</small><span id="characterArchiveReaderIndex"></span></header><div class="character-archive-reader-scroll"><div class="character-archive-reader-kicker" id="characterArchiveReaderKicker"></div><h2 id="characterArchiveReaderTitle"></h2><article id="characterArchiveReaderContent"></article></div><footer><button type="button" id="characterArchivePrev" onclick="OCCharacterArchive.moveChapter(-1)"><i class="fa-solid fa-arrow-left"></i> 上一章</button><button type="button" id="characterArchiveNext" onclick="OCCharacterArchive.moveChapter(1)">下一章 <i class="fa-solid fa-arrow-right"></i></button></footer></div>';document.body.append(reader);
    const editor=document.createElement('div');editor.id='characterArchiveEditor';editor.className='modal-backdrop character-archive-editor';editor.innerHTML='<form class="character-archive-editor-shell" onsubmit="OCCharacterArchive.saveEditor(event)"><header><div><small>CHARACTER CHRONICLE · EDITOR</small><h3 id="characterArchiveEditorTitle"></h3></div><button type="button" onclick="OCCharacterArchive.closeEditor()" aria-label="關閉編輯器">×</button></header><div class="character-archive-editor-fields"><input type="hidden" id="characterArchiveEditKind"><input type="hidden" id="characterArchiveEditId"><label>標題<input id="characterArchiveEditTitle" maxlength="100" required placeholder="寫下這一頁的標題"></label><label id="characterArchiveContentLabel">內容<textarea id="characterArchiveEditContent" rows="12" placeholder="在這裡記下人物的故事、事件或秘密……"></textarea></label></div><footer><button type="button" onclick="OCCharacterArchive.closeEditor()">取消</button><button type="submit"><i class="fa-solid fa-check"></i> 儲存變更</button></footer></form>';document.body.append(editor);
  }
  function open(id){const char=characters.find(row=>String(row.id)===String(id));if(!char)return;ensureShell();activeCharId=String(id);editing=false;readerChapterId='';$('characterArchiveModal').classList.remove('is-editing');$('characterArchiveEditToggle').setAttribute('aria-pressed','false');render();$('characterArchiveModal').classList.add('active');}
  function close(){if($('characterArchiveEditor')?.classList.contains('active')&&!closeEditor())return;if(window.OCInterrogation?.close()===false)return;$('characterArchiveReader')?.classList.remove('active');$('characterArchiveModal')?.classList.remove('active');activeCharId='';editing=false;}
  function toggleEdit(){editing=!editing;const modal=$('characterArchiveModal'),button=$('characterArchiveEditToggle');modal.classList.toggle('is-editing',editing);button.setAttribute('aria-pressed',String(editing));button.setAttribute('aria-label',editing?'關閉人物檔案編輯模式':'開啟人物檔案編輯模式');window.OCInterrogation?.refreshEditing?.();}
  function render(){const char=getChar(),modal=$('characterArchiveModal');if(!char||!modal)return;const book=getBook(char),entries=chapters(char);setPalette(modal,char);$('characterArchiveName').textContent=char.name;$('characterArchiveSubtitle').textContent=[char.englishName,char.occupation].filter(Boolean).join(' · ')||'每個人的故事，都值得被珍藏。';$('characterArchivePortrait').innerHTML=char.avatar?`<img src="${esc(char.avatar)}" alt="${esc(char.name)}" onerror="this.remove()">`:`<span>${esc(char.name.slice(0,1))}</span>`;$('characterArchiveCount').textContent=`${entries.length} 篇人物記事`;
    $('characterArchiveBody').innerHTML=`<div class="timeline-book-intro character-archive-intro"><div class="timeline-book-monogram character-archive-monogram" aria-hidden="true"><i class="fa-solid fa-book-open-reader"></i></div><div class="character-archive-book-copy"><small>THE CHARACTER ARCHIVE · ${entries.length} CHAPTERS</small><h3>${esc(book.title||`${char.name}記事`)}</h3><p>${esc(book.description||'翻開書頁，記錄這個人的過往與此刻。')}</p></div><div class="timeline-book-manage"><button type="button" onclick="OCCharacterArchive.editBook()"><i class="fa-solid fa-pen"></i> 編輯書籍資料</button></div></div><section class="character-archive-profile"><div><strong>檔案主人</strong><p>${esc(char.name)}${char.englishName?` <span>${esc(char.englishName)}</span>`:''}</p></div>${char.tags?.length?`<div class="character-archive-tags">${char.tags.slice(0,6).map(tag=>`<span>${esc(tag)}</span>`).join('')}</div>`:''}</section><section class="timeline-book-chapters character-archive-chapters"><div class="timeline-book-chapters-heading"><small>TABLE OF CONTENTS</small><h4>人物記事目錄</h4><button type="button" class="timeline-book-new-chapter" onclick="OCCharacterArchive.editChapter()"><i class="fa-solid fa-plus"></i> 新增記事</button></div>${entries.length?entries.map((chapter,index)=>`<div class="timeline-book-chapter-row"><button type="button" class="timeline-book-chapter" onclick="OCCharacterArchive.read('${esc(chapter.id)}')"><span class="timeline-book-chapter-number">${String(index+1).padStart(2,'0')}</span><span class="timeline-book-chapter-copy"><strong>${esc(chapter.title||'未命名記事')}</strong><small>${esc((chapter.content||'').trim().slice(0,72)||'點開閱讀這篇人物記事')}</small></span><i class="fa-solid fa-arrow-up-right-from-square"></i></button><div class="timeline-book-chapter-actions"><button type="button" onclick="OCCharacterArchive.editChapter('${esc(chapter.id)}')" aria-label="編輯${esc(chapter.title)}"><i class="fa-solid fa-pen"></i></button><button type="button" onclick="OCCharacterArchive.deleteChapter('${esc(chapter.id)}')" aria-label="刪除${esc(chapter.title)}"><i class="fa-solid fa-trash-can"></i></button></div></div>`).join(''):'<div class="character-archive-empty"><i class="fa-solid fa-feather-pointed"></i><h4>還沒有寫下第一篇記事</h4><p>開啟右上角編輯模式，替這個人留下故事的第一頁。</p><button type="button" class="timeline-book-new-chapter" onclick="OCCharacterArchive.editChapter()"><i class="fa-solid fa-plus"></i> 寫下第一篇</button></div>'}</section>`;}
  function editBook(){if(!editing)return;openEditor('book');}
  function editChapter(id=''){if(!editing)return;openEditor('chapter',id);}
  function openEditor(kind,id=''){const char=getChar();if(!char)return;const book=getBook(char),chapter=chapters(char).find(row=>String(row.id)===String(id));if(kind==='chapter'&&id&&!chapter)return;$('characterArchiveEditKind').value=kind;$('characterArchiveEditId').value=id;$('characterArchiveEditorTitle').textContent=kind==='book'?'編輯人物檔案':chapter?'編輯記事章節':'新增記事章節';$('characterArchiveEditTitle').value=kind==='book'?(book.title||`${char.name}記事`):(chapter?.title||'');$('characterArchiveEditContent').value=kind==='book'?(book.description||''):(chapter?.content||'');$('characterArchiveContentLabel').firstChild.textContent=kind==='book'?'書籍簡介':'記事正文';editorSnapshot=JSON.stringify([$('characterArchiveEditTitle').value,$('characterArchiveEditContent').value]);$('characterArchiveEditor').classList.add('active');$('characterArchiveEditTitle').focus();}
  function closeEditor(){const editor=$('characterArchiveEditor');if(!editor?.classList.contains('active'))return true;const current=JSON.stringify([$('characterArchiveEditTitle').value,$('characterArchiveEditContent').value]);if(current!==editorSnapshot&&!confirm('記事尚未儲存，確定要放棄這次修改嗎？'))return false;editor.classList.remove('active');editorSnapshot='';return true;}
  function saveEditor(event){event.preventDefault();const char=getChar();if(!char)return;const kind=$('characterArchiveEditKind').value,id=$('characterArchiveEditId').value,title=$('characterArchiveEditTitle').value.trim(),content=$('characterArchiveEditContent').value.trim();if(!title){$('characterArchiveEditTitle').focus();return;}const book=char.archiveBook||(char.archiveBook={title:`${char.name}記事`,description:'',chapters:[]});if(!Array.isArray(book.chapters))book.chapters=[];if(kind==='book'){book.title=title;book.description=content;}else{const existing=book.chapters.find(row=>String(row.id)===id);if(existing){existing.title=title;existing.content=content;}else book.chapters.push({id:`entry_${Date.now()}_${Math.random().toString(36).slice(2,7)}`,title,content});}saveStateToLocalStorage();editorSnapshot=JSON.stringify([$('characterArchiveEditTitle').value,$('characterArchiveEditContent').value]);$('characterArchiveEditor').classList.remove('active');render();}
  function deleteChapter(id){if(!editing)return;const char=getChar(),book=char?.archiveBook,chapter=book?.chapters?.find(row=>String(row.id)===String(id));if(!chapter||!confirm(`確定刪除「${chapter.title}」？此篇記事內容將無法復原。`))return;book.chapters=book.chapters.filter(row=>String(row.id)!==String(id));saveStateToLocalStorage();render();}
  function read(id){const char=getChar(),entries=chapters(char),index=entries.findIndex(row=>String(row.id)===String(id));if(index<0)return;const chapter=entries[index],reader=$('characterArchiveReader');readerChapterId=String(id);setPalette(reader,char);$('characterArchiveReaderIndex').textContent=`${String(index+1).padStart(2,'0')} / ${String(entries.length).padStart(2,'0')}`;$('characterArchiveReaderKicker').textContent=`${char.name} · 人物記事`;$('characterArchiveReaderTitle').textContent=chapter.title;$('characterArchiveReaderContent').textContent=chapter.content||'這一頁尚未寫下內容。';$('characterArchivePrev').disabled=index===0;$('characterArchiveNext').disabled=index===entries.length-1;reader.classList.add('active');reader.querySelector('.character-archive-reader-scroll').scrollTop=0;}
  function closeReader(){$('characterArchiveReader')?.classList.remove('active');readerChapterId='';}
  function moveChapter(step){const entries=chapters(getChar()),index=entries.findIndex(row=>String(row.id)===readerChapterId),next=entries[index+step];if(next)read(next.id);}
  function exportText(selected){let text=`# 完整人物記事\n生成時間：${new Date().toLocaleString()}\n包含角色 (${selected.length} 位)：${selected.map(char=>char.name).join('、')||'無'}\n\n`;for(const char of selected){const book=getBook(char),entries=chapters(char);text+=`## ${char.name}${char.englishName?` (${char.englishName})`:''}\n### ${book.title||`${char.name}記事`}\n`;if(book.description)text+=`${book.description}\n`;text+='\n';if(entries.length){entries.forEach((chapter,index)=>{text+=`#### ${String(index+1).padStart(2,'0')} ${chapter.title||'未命名記事'}\n${chapter.content||'（尚無內容）'}\n\n`;});}else text+='（尚無人物記事章節）\n\n';text+='-----------------------------------\n\n';}return text;}
  window.OCCharacterArchive={open,close,toggleEdit,editBook,editChapter,closeEditor,saveEditor,deleteChapter,read,closeReader,moveChapter,exportText,isEditing:()=>editing,activeCharacter:()=>activeCharId};
})();
