/* Visual review of the exact choices used by manual cloud merge. */
(()=>{'use strict';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const names={characters:'人物',paros:'世界觀',factions:'陣營',books:'書籍',documents:'文檔',timelines:'時間線',mediaLibrary:'媒體',cps:'CP',rankings:'排名',bio:'人物敘述',description:'敘述',content:'正文',story:'故事',summary:'摘要',name:'名稱',title:'標題',avatar:'頭像',personality:'性格',appearance:'外貌',background:'背景',relationships:'人物關係',callName:'稱呼',opinion:'看法',charIds:'關聯人物',events:'事件',sections:'段落',themeColor:'主題色',primary:'主色',secondary:'副色',when:'時間',value:'設定內容',mainTimelineOrder:'主線節點順序',visualNovel:'劇場',visualNovelPage:'場景與音樂配置',cues:'場景與音樂標註',scriptText:'劇本',library:'CP 文庫',textExportEnabled:'允許文字輸出',subject:'排名主題',tiers:'排名階級',entries:'排名人物',poolIds:'卡池人物',cpIds:'CP 卡池',linkedBookIds:'關聯書籍',linkedDocumentIds:'關聯文檔',isMainline:'主線／番外',targetName:'對象',targetId:'關聯對象'};
const empty=v=>v===undefined||v===null||v===''||Array.isArray(v)&&!v.length;
const text=v=>v===undefined?'不存在／已刪除':v===null||v===''?'（空白）':typeof v==='string'?v:JSON.stringify(v,null,2);
const size=v=>SavePreference.amount(v);
const readable=v=>v&&typeof v==='object'&&!Array.isArray(v)&&v.targetName?['對象：'+v.targetName,'稱呼：'+(v.callName||'（空白）'),'看法：'+(v.opinion||'（空白）'),'主線：'+(v.isMainline?'是':'否')].join('\n'):v;
const cueSummary=v=>{const cues=v?.cues||{};return Object.keys(cues).length+' 處場景／配樂標註（手動 '+Object.values(cues).filter(c=>c.sceneSource==='manual'||c.musicSource==='manual').length+' 處）';};
function excerpt(a,b){a=text(readable(a));b=text(readable(b));let first=0,last=0;while(first<Math.min(a.length,b.length)&&a[first]===b[first])first++;while(last<Math.min(a.length,b.length)-first&&a[a.length-last-1]===b[b.length-last-1])last++;const one=s=>{const end=s.length-last,lead=s.slice(Math.max(0,first-90),first),changed=s.slice(first,end),tail=s.slice(end,end+90);return (first>90?'…':'')+esc(lead)+'<mark>'+esc(changed.slice(0,1200))+(changed.length>1200?'…':'')+'</mark>'+esc(tail)+(last>90?'…':'');};return [one(a),one(b)];}
window.CloudSaveReview={mount(host,preview,C){
let active='',filter='attention',query='',limit=20;const groups=new Map();
for(const item of preview.items){item.decisions||={};for(const d of item.changes){const key=item.scope+':'+d.group+':'+d.id;let group=groups.get(key);if(!group){const local=item.local.data[d.group]?.find(row=>String(row.id)===String(d.id)),remote=item.remote.data[d.group]?.find(row=>String(row.id)===String(d.id));group={key,item,rows:[],name:local?.name||remote?.name||local?.title||remote?.title||d.recordName||d.id,avatar:local?.avatar||remote?.avatar,group:d.group};groups.set(key,group);}group.rows.push(d);}}
const choice=(g,d)=>g.item.decisions[d.key]||d.choice;
const replaces=(g,d)=>!isOrder(d)&&choice(g,d)==='remote'&&!empty(d.local)&&!C.equal(d.local,d.remote);
const potential=d=>!empty(d.local)&&!C.equal(d.local,d.remote);
const attention=g=>g.rows.some(d=>isOrder(d)||replaces(g,d)||choice(g,d)==='local'||d.remote===undefined);
const writing=d=>['characterRelationship','perspectiveTarget'].includes(d.kind)||!d.kind&&['characters','documents','books','paros'].includes(d.group)||d.kind==='recordField'&&(typeof d.local==='string'||typeof d.remote==='string')&&!['id','updatedAt','createdAt','modifiedAt','avatar','url','colorA','colorB','kind','type','bookId','storage'].includes(d.path.at(-1));
const isOrder=d=>['recordOrder','collectionOrder'].includes(d.kind)||d.path?.at(-1)==='mainTimelineOrder';
const label=d=>isOrder(d)?(d.path?.map(part=>typeof part==='string'?(names[part]||part):'項目').join(' › ')||'清單')+'排列順序':d.kind==='recordField'?d.path.map(part=>typeof part==='string'?(names[part]||part):'項目 '+part.id).join(' › '):d.kind==='characterRelationship'?'與 '+d.targetName+' 的稱呼／看法':d.kind==='perspectiveTarget'?'視角 · '+d.targetName:'整筆'+(names[d.group]||'資料');
const effect=(g,d)=>{if(isOrder(d)&&choice(g,d)==='merged')return '保留預選排列並加入新增節點';if(isOrder(d))return '採用'+(choice(g,d)==='local'?'本機':'雲端')+'排列順序';if(choice(g,d)==='copy')return '保留兩份';if(choice(g,d)==='merged')return '保留較完整欄位與新增項目';if(choice(g,d)==='local')return empty(d.remote)?'保留本機新增內容':'保留本機內容';if(d.remote===undefined)return '將刪除此項';if(empty(d.local))return '加入雲端內容';return empty(d.remote)?'將清空本機內容':size(d.remote)<size(d.local)?'將替換本機，內容較短':'將替換本機內容';};
host.innerHTML='<section class="save-review"><div class="save-review-heading"><div><small>SYNC PREVIEW</small><h3>同步後，哪些內容會改變？</h3><p>預設採用雲端；本機字數較多或雲端缺少的內容會保留本機，字數相同用雲端。清單會保留兩端新增項目。確認後才套用，可手動改用較短版本或刪除。</p></div><div class="save-review-counts"></div></div><div class="save-review-tools"><input type="search" data-review-search placeholder="搜尋角色、書籍或文檔名稱" aria-label="搜尋同步項目"><button type="button" class="btn btn-outline" data-review-protect>保護全部本機內容</button></div><div class="save-review-tabs"><button type="button" data-review-filter="attention">本機保留／刪除</button><button type="button" data-review-filter="all">全部差異</button><button type="button" data-review-filter="incoming">雲端更新</button><button type="button" data-review-filter="text">文字內容</button></div><div class="save-review-layout"><nav class="save-review-list" aria-label="有差異的角色與文檔"></nav><div class="save-review-detail"></div></div><footer><p data-review-result></p><div><button type="button" class="btn btn-outline" data-cloud="cancel">取消</button><button type="button" class="btn btn-primary" data-cloud="confirm">確認這些選擇並'+(preview.direction==='upload'?'上傳':preview.direction==='restore'?'復原':'合併')+'</button></div></footer></section>';
const list=host.querySelector('.save-review-list'),detail=host.querySelector('.save-review-detail');
function localize(){if(preview.direction!=='import')return;host.querySelectorAll('small,option,button,p,label').forEach(node=>{for(const child of node.childNodes)if(child.nodeType===3)child.textContent=child.textContent.replaceAll('雲端','讀檔');});}
function render(reset=false){if(reset)limit=20;const all=[...groups.values()],rows=all.flatMap(g=>g.rows.map(d=>({g,d}))),danger=rows.filter(({g,d})=>replaces(g,d)),conflicts=rows.filter(({d})=>d.conflict),visible=all.filter(g=>(!query||String(g.name+' '+(names[g.group]||g.group)).toLocaleLowerCase().includes(query))&&(filter==='all'||filter==='attention'&&attention(g)||filter==='incoming'&&g.rows.some(d=>choice(g,d)==='remote')||filter==='text'&&g.rows.some(writing)));host.querySelector('.save-review-counts').innerHTML='<span><b>'+all.length+'</b> 個項目</span><span><b>'+conflicts.length+'</b> 處衝突</span><span class="is-risk"><b>'+danger.length+'</b> 處將替換本機</span>';host.querySelector('[data-review-result]').textContent='確認後：'+danger.length+' 處本機內容會被替換；'+rows.filter(({g,d})=>choice(g,d)==='local').length+' 處保留本機。';host.querySelectorAll('[data-review-filter]').forEach(button=>{button.classList.toggle('is-active',button.dataset.reviewFilter===filter);button.setAttribute('aria-pressed',String(button.dataset.reviewFilter===filter));});if(!visible.some(g=>g.key===active))active=visible[0]?.key||'';
const leftTop=list.scrollTop,rightTop=reset?0:detail.scrollTop;list.innerHTML=visible.length?visible.map(g=>{const risky=g.rows.filter(d=>replaces(g,d)).length,conflict=g.rows.filter(d=>d.conflict).length;return '<button type="button" class="save-review-item '+(active===g.key?'is-active':'')+'" data-review-item="'+esc(g.key)+'" aria-pressed="'+(active===g.key)+'">'+(g.avatar?'<img src="'+esc(g.avatar)+'" alt="">':'<span class="save-review-symbol">'+esc(String(g.name).slice(0,1))+'</span>')+'<span><small>'+esc(names[g.group]||g.group)+'</small><strong>'+esc(g.name)+'</strong><em>'+g.rows.length+' 處差異'+(risky?' · '+risky+' 處覆蓋':conflict?' · 有衝突':' · 保留／合併')+'</em></span></button>';}).join(''):'<p class="save-review-empty">'+(query?'沒有符合搜尋的項目。':'目前沒有需留意的項目，可切到「全部差異」查看。')+'</p>';list.scrollTop=leftTop;
const g=groups.get(active);if(!g){detail.innerHTML='<div class="save-review-empty">✓ 本機內容受到保護<br><small>選擇「全部差異」查看雲端新增與自動合併。</small></div>';localize();return;}
detail.innerHTML='<header><div><small>'+esc(names[g.group]||g.group)+'</small><h4>'+esc(g.name)+'</h4></div><button type="button" class="btn btn-outline" data-review-protect-item>保護此項本機內容</button></header>'+[...g.rows].filter(d=>filter!=='text'||writing(d)).sort((a,b)=>Number(replaces(g,b)||b.conflict)-Number(replaces(g,a)||a.conflict)).slice(0,limit).map((d,i)=>{const orderText=(side)=>{const record=g.item[side].data[d.group]?.find(row=>String(row.id)===d.id);let rows=d.kind==='collectionOrder'?g.item[side].data[d.group]:record;for(const part of d.path||[])rows=typeof part==='object'?rows?.find(row=>String(row.id)===part.id):rows?.[part];return (d[side]||[]).map((id,index)=>{let name;if(id&&typeof id==='object'){const sources=g.item[side].data.timelines||[],source=id.kind==='linkedEvent'?sources.find(t=>String(t.id)===String(id.timelineId)):id.kind==='timeline'?sources.find(t=>String(t.id)===String(record?.linkedTimelines?.find(link=>link.id===id.id)?.timelineId)):record;name=id.kind==='timeline'?(record?.linkedTimelines?.find(link=>link.id===id.id)?.title||source?.name||'關聯時間線入口'):source?.events?.find(e=>e.id===(id.eventId||id.id))?.title||'關聯事件';}else name=rows?.find(row=>String(row.id)===id)?.title||rows?.find(row=>String(row.id)===id)?.name||rows?.find(row=>String(row.id)===id)?.subject||id;return (index+1)+'. '+name;}).join('\n');};
const selected=choice(g,d),risk=replaces(g,d),diff=isOrder(d)?[esc(orderText('local')),esc(orderText('remote'))]:d.path?.[0]==='visualNovelPage'?[esc(cueSummary(d.local)),esc(cueSummary(d.remote))]:excerpt(d.local,d.remote);return '<article class="oc-cloud-row save-review-field '+(risk?'is-risk':'')+'"><div class="save-review-field-top"><strong>'+esc(label(d))+'</strong><span>'+esc(effect(g,d))+'</span></div>'+'<p class="save-review-recommendation">'+esc(d.recommendation||'')+'</p>'+(!isOrder(d)&&potential(d)&&size(d.local)>size(d.remote)?'<p class="save-review-warning">本機比雲端多 '+(size(d.local)-size(d.remote))+' 字／資料量，採用雲端可能移除你新增的內容。</p>':'')+'<label>同步後使用<select data-choice="'+i+'" data-scope-key="'+g.item.scope+'" data-change-key="'+esc(d.key)+'"><option value="local" '+(selected==='local'?'selected':'')+'>保留本機</option><option value="remote" '+(selected==='remote'?'selected':'')+'>採用雲端</option>'+(d.merged!==undefined&&d.merged!==null?'<option value="merged" '+(selected==='merged'?'selected':'')+'>保留較完整欄位與兩端新增項目</option>':'')+(!d.kind&&d.local&&d.remote&&!C.mapFields.has(d.group)?'<option value="copy" '+(selected==='copy'?'selected':'')+'>保留兩份</option>':'')+'</select></label><div class="save-review-comparison"><section><small>本機 · '+(isOrder(d)?(d.local||[]).length+' 項':size(d.local)+' 字／資料量')+'</small><div>'+diff[0]+'</div></section><section><small>雲端 · '+(isOrder(d)?(d.remote||[]).length+' 項':size(d.remote)+' 字／資料量')+'</small><div>'+diff[1]+'</div></section></div><details><summary>查看完整內容</summary><div class="oc-cloud-compare"><div>本機<pre>'+esc(text(d.local))+'</pre></div><div>雲端<pre>'+esc(text(d.remote))+'</pre></div></div></details></article>';}).join('')+(g.rows.length>limit?'<button type="button" class="btn btn-outline" data-review-more>再顯示 20 處差異（還有 '+(g.rows.length-limit)+' 處）</button>':'');detail.scrollTop=rightTop;localize();
}
host.addEventListener('input',event=>{if(event.target.matches('[data-review-search]')){query=event.target.value.trim().toLocaleLowerCase();render(true);}});
host.addEventListener('change',event=>{if(!event.target.matches('[data-choice]'))return;const g=groups.get(active);g.item.decisions[event.target.dataset.changeKey]=event.target.value;const key=event.target.dataset.changeKey;render();host.querySelector('[data-change-key="'+CSS.escape(key)+'"]')?.focus({preventScroll:true});});
host.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;if(button.hasAttribute('data-review-more')){limit+=20;render();}else if(button.dataset.reviewItem){active=button.dataset.reviewItem;render(true);}else if(button.dataset.reviewFilter){filter=button.dataset.reviewFilter;render(true);}else if(button.hasAttribute('data-review-protect')||button.hasAttribute('data-review-protect-item')){const targets=button.hasAttribute('data-review-protect')?[...groups.values()]:[groups.get(active)];for(const g of targets)for(const d of g.rows)if(potential(d))g.item.decisions[d.key]='local';filter='all';render();}});
if(preview.direction==='restore'){host.querySelector('.save-review-heading h3').textContent='從雲端復原：哪些本機內容會被取代？';host.querySelector('.save-review-heading p').textContent='完整復原預設採用雲端整份資料。確認後才會套用；可先將部分欄位改為保留本機，或取消並改用合併雲端資料。';}if(![...groups.values()].some(attention))filter='all';render(true);
}};
})();
