/* CP library: private books plus links to workshop books and articles. */
(()=>{'use strict';
const $=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch])),uid=prefix=>`${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
let cpId='',selected='',editing=false,editorKind='',editorId='',snapshot='',readerId='';
const cp=()=>cps.find(row=>String(row.id)===cpId),data=()=>cp()?.library||{books:[],linkedBookIds:[]},ownBook=()=>data().books.find(row=>row.id===selected),save=()=>{saveStateToLocalStorage();render();};
function ensure(){if($('cpLibraryModal'))return;
const modal=document.createElement('div');modal.id='cpLibraryModal';modal.className='modal-backdrop timeline-books-backdrop character-archive-backdrop cp-library-modal';modal.innerHTML=`<div class="timeline-books-shell character-archive-shell"><div class="cp-library-scroll"><header class="timeline-books-hero character-archive-hero cp-library-hero"><button type="button" class="timeline-books-return" data-cpl="close" aria-label="返回 CP 卡庫">←</button><small>CP CHRONICLE · PRIVATE READING ROOM</small><div class="character-archive-hero-main"><div id="cpLibraryPortrait" class="cp-library-portraits"></div><div class="cp-library-hero-copy"><h2 id="cpLibraryName"></h2><p id="cpLibrarySubtitle"></p></div></div><span id="cpLibraryCount" class="character-archive-count"></span><button type="button" class="timeline-books-edit-toggle" data-cpl="edit" id="cpLibraryEditToggle" aria-pressed="false">✎ <span>編輯模式</span></button></header><nav id="cpLibraryBooks" class="cp-library-books" aria-label="選擇 CP 書籍"></nav><main id="cpLibraryBody" class="timeline-books-body character-archive-body"></main></div></div>`;document.body.append(modal);
const reader=document.createElement('div');reader.id='cpLibraryReader';reader.className='modal-backdrop character-archive-reader';reader.innerHTML='<div class="character-archive-reader-shell"><header><button type="button" data-cpl="close-reader">← 章節目錄</button><small>RELATIONSHIP CHRONICLE</small><span id="cpLibraryReaderIndex"></span></header><div class="character-archive-reader-scroll"><div id="cpLibraryReaderPeople" class="character-archive-reader-kicker"></div><h2 id="cpLibraryReaderTitle"></h2><article id="cpLibraryReaderContent"></article></div><footer><button type="button" data-cpl="prev">← 上一章</button><button type="button" data-cpl="next">下一章 →</button></footer></div>';document.body.append(reader);
const editor=document.createElement('div');editor.id='cpLibraryEditor';editor.className='modal-backdrop character-archive-editor';editor.innerHTML=`<form class="character-archive-editor-shell"><header><h3 id="cpLibraryEditorHeading"></h3><button type="button" data-cpl="close-editor" aria-label="關閉編輯器">×</button></header><div class="character-archive-editor-fields"><label>標題<input id="cpLibraryTitle" required maxlength="150"></label><label id="cpLibraryContentLabel">內容<textarea id="cpLibraryContent" rows="12"></textarea></label><fieldset id="cpLibraryPeople"><legend>關聯人物（可選 CP 成員以外的人物）</legend><input id="cpLibraryPeopleSearch" type="search" placeholder="搜尋人物名稱" aria-label="搜尋文檔關聯人物"><div class="cp-library-people"></div></fieldset><div id="cpLibraryLinkFields" hidden><label>關聯類型<select id="cpLibraryLinkKind"><option value="book">書籍</option><option value="document">文檔</option></select></label><label>搜尋<input type="search" id="cpLibraryResourceSearch" placeholder="搜尋書名或文檔標題"></label><label>選擇要關聯的資料<select id="cpLibraryResource"></select></label><label class="cp-library-visibility"><input type="checkbox" id="cpLibraryShowGlobal" checked> 關聯的書籍顯示於同人書籍處</label><p>書籍會以連結加入文庫；修改原書或文檔後，這裡也會顯示最新內容。</p></div></div><footer><button type="button" data-cpl="close-editor">取消</button><button type="submit">儲存變更</button></footer></form>`;document.body.append(editor);
for(const root of [modal,reader,editor])root.addEventListener('click',click);editor.querySelector('form').addEventListener('submit',saveEditor);editor.addEventListener('input',event=>{if(event.target.id==='cpLibraryPeopleSearch'){const q=event.target.value.trim().toLocaleLowerCase();editor.querySelectorAll('.cp-library-people label').forEach(el=>el.hidden=!el.textContent.toLocaleLowerCase().includes(q));}if(event.target.id==='cpLibraryResourceSearch')resources();});editor.addEventListener('change',event=>{if(event.target.id==='cpLibraryLinkKind')resources();if(event.target.id==='cpLibraryResource')resourceVisibility();});
}
function palette(){const row=cp();if(!row)return;const people=(row.members||[]).map(m=>OCRecordPolicy.character(m.charId)).filter(Boolean),colors=resolveCpGradientColors(row,people),luminance=hex=>[1,3,5].map(i=>parseInt(hex.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((sum,v,i)=>sum+v*[.2126,.7152,.0722][i],0),ink=colors.reduce((sum,c)=>sum+luminance(c),0)/colors.length>.38?'#211d27':'#fffaf7';for(const id of ['cpLibraryModal','cpLibraryReader','cpLibraryEditor']){const root=$(id);root.style.setProperty('--gallery-a',colors[0]);root.style.setProperty('--gallery-b',colors[1]);root.style.setProperty('--world-a',colors[0]);root.style.setProperty('--world-b',colors[1]);root.style.setProperty('--world-ink',ink);root.style.setProperty('--cp-library-gradient',cpGradientCss(colors));root.style.setProperty('--book-a',colors[0]);root.style.setProperty('--book-b',colors[1]);root.style.setProperty('--book-ink',ink);root.style.setProperty('--book-paper','var(--bg-primary)');root.style.setProperty('--book-paperInk','var(--text-main)');}return people;}
function open(id){if(!cps.some(row=>String(row.id)===String(id)))return;ensure();cpId=String(id);selected='';editing=false;readerId='';render();$('cpLibraryModal').classList.add('active');}
function close(){if(!closeEditor())return;closeReader();$('cpLibraryModal')?.classList.remove('active');cpId='';}
function booksList(){return [...data().books.map(row=>({...row,key:row.id,linked:false})),...(data().linkedBookIds||[]).map(id=>books.find(row=>row.id===id)).filter(Boolean).map(row=>({...row,key:'linked:'+row.id,linked:true}))];}
function chapters(){const book=booksList().find(row=>row.key===selected);if(!book)return [];if(book.linked)return documents.filter(doc=>doc.bookId===book.id).map(doc=>({...doc,linked:true}));const local=book.documents||[],linked=(book.linkedDocumentIds||[]).map(id=>documents.find(doc=>doc.id===id)).filter(Boolean).map(doc=>({...doc,linked:true}));return [...local,...linked];}
function render(){const row=cp();if(!row||!$('cpLibraryModal'))return;const list=booksList();if(!list.some(b=>b.key===selected))selected=list[0]?.key||'';const people=palette();$('cpLibraryModal').classList.toggle('is-editing',editing);$('cpLibraryEditToggle').setAttribute('aria-pressed',String(editing));$('cpLibraryEditToggle').innerHTML=editing?'✓ <span>完成編輯</span>':'✎ <span>編輯模式</span>';$('cpLibraryName').textContent=row.name;$('cpLibrarySubtitle').textContent=people.map(person=>person.name).join(' × ')||'共同故事的私人閱讀室';$('cpLibraryCount').textContent=list.length+' 本書籍 · '+list.reduce((count,book)=>count+(book.linked?documents.filter(doc=>doc.bookId===book.id).length:(book.documents||[]).length+(book.linkedDocumentIds||[]).filter(id=>documents.some(doc=>doc.id===id)).length),0)+' 篇文檔';$('cpLibraryPortrait').classList.toggle('is-trio',people.length===3);$('cpLibraryPortrait').innerHTML=people.slice(0,3).map(person=>`<span class="cp-library-portrait-frame" title="${esc(person.name)}">${person.avatar?`<img src="${esc(person.avatar)}" alt="${esc(person.name)}">`:esc(person.name.slice(0,1))}</span>`).join('');
$('cpLibraryBooks').innerHTML=list.map(b=>`<button type="button" data-cpl="book" data-id="${esc(b.key)}" aria-pressed="${b.key===selected}"><i class="fa-solid ${b.linked?'fa-link':'fa-book'}"></i> ${esc(b.title)}</button>`).join('')+(editing?'<button type="button" data-cpl="new-book">＋ 新建書籍</button><button type="button" data-cpl="link">＋ 關聯書籍／文檔</button>':'');
const book=list.find(b=>b.key===selected),entries=chapters(),body=$('cpLibraryBody');if(!book){body.innerHTML=`<div class="timeline-book-intro character-archive-intro"><div class="timeline-book-monogram character-archive-monogram"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M3 5.5c3-1.4 5.7-1.2 8 .2v15c-2.3-1.4-5-1.6-8-.2V5.5Zm10 .2c2.3-1.4 5-1.6 8-.2v15c-3-1.4-5.7-1.2-8 .2v-15Z"/></svg></div><div class="character-archive-book-copy"><small>THE CP ARCHIVE · 0 CHAPTERS</small><h3>${esc(row.name)}文庫</h3><p>翻開書頁，收藏彼此的相遇與此刻。</p></div></div><div class="character-archive-profile"><div><strong>文庫主人</strong><p>${esc(row.name)}</p></div><div class="character-archive-tags">${people.map(person=>'<span>'+esc(person.name)+'</span>').join('')}</div></div><section class="timeline-book-chapters"><div class="timeline-book-chapters-heading"><small>TABLE OF CONTENTS</small><h4>CP 文庫目錄</h4></div><div class="character-archive-empty"><span class="cp-library-empty-feather" aria-hidden="true">✎</span><h4>還沒有寫下第一篇故事</h4><p>開啟右上角編輯模式，新建書籍或關聯已有文檔。</p></div></section>`;return;}
body.innerHTML=`<div class="timeline-book-intro character-archive-intro"><div class="timeline-book-monogram character-archive-monogram"><svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M3 5.5c3-1.4 5.7-1.2 8 .2v15c-2.3-1.4-5-1.6-8-.2V5.5Zm10 .2c2.3-1.4 5-1.6 8-.2v15c-3-1.4-5.7-1.2-8 .2v-15Z"/></svg></div><div class="character-archive-book-copy"><small>${book.linked?'LINKED WORLD BOOK':'CP LIBRARY'} · ${entries.length} CHAPTERS</small><h3>${esc(book.title)}</h3><p>${esc(book.description||'在這裡，慢慢收藏這段關係的故事。')}</p></div>${editing?`<div class="cp-library-tools">${book.linked?'':`<button type="button" data-cpl="edit-book">編輯書籍</button>`}<button type="button" data-cpl="export">輸出文庫</button><button type="button" data-cpl="remove-book">${book.linked?'解除關聯':'刪除書籍'}</button></div>`:''}</div><div class="character-archive-profile"><div><strong>文庫主人</strong><p>${esc(row.name)}</p></div><div class="character-archive-tags">${people.map(person=>'<span>'+esc(person.name)+'</span>').join('')}</div></div>${book.linked&&editing?`<label class="cp-library-visibility"><input type="checkbox" data-cpl-visibility ${!book.hideFromDocuments?'checked':''}> 此書同時顯示於同人書籍處</label>`:''}<section class="timeline-book-chapters character-archive-chapters"><div class="timeline-book-chapters-heading"><small>TABLE OF CONTENTS</small><h4>文庫目錄</h4>${editing?`<button type="button" data-cpl="new-document">＋ 新建文檔</button>`:''}</div>${entries.map((doc,index)=>`<div class="timeline-book-chapter-row"><button type="button" class="timeline-book-chapter" data-cpl="read" data-id="${esc(doc.id)}"><span class="timeline-book-chapter-number">${String(index+1).padStart(2,'0')}</span><span class="timeline-book-chapter-copy"><strong>${esc(doc.title)} ${doc.linked?'<small>關聯文檔</small>':''}</strong><small>${esc((doc.charIds||[]).map(id=>OCRecordPolicy.character(id)?.name).filter(Boolean).join('、')||String(doc.content||'').slice(0,72))}</small></span><i class="fa-solid fa-arrow-up-right-from-square"></i></button>${editing?`<div class="cp-library-tools"><button type="button" data-cpl="edit-document" data-id="${esc(doc.id)}">編輯</button>${!book.linked?`<button type="button" data-cpl="remove-document" data-id="${esc(doc.id)}">${doc.linked?'解除關聯':'刪除'}</button>`:''}</div>`:''}</div>`).join('')||'<div class="character-archive-empty"><span class="cp-library-empty-feather" aria-hidden="true">✎</span><h4>還沒有寫下第一篇故事</h4><p>開啟編輯模式，記下彼此的第一篇故事。</p></div>'}</section>`;
body.querySelector('[data-cpl-visibility]')?.addEventListener('change',event=>{const original=books.find(b=>b.id===book.id);if(original){original.hideFromDocuments=!event.target.checked;saveStateToLocalStorage();renderDocumentsModule();}});
}
function openEditor(kind,id=''){if(!editing)return;editorKind=kind;editorId=id;const book=booksList().find(b=>b.key===selected),doc=chapters().find(d=>d.id===id),row=kind==='book'?book:doc;ensure();$('cpLibraryEditorHeading').textContent={book:id?'編輯書籍':'新建書籍',document:id?'編輯文檔':'新建文檔',link:'關聯書籍／文檔'}[kind];$('cpLibraryTitle').value=id?row?.title||'':'';$('cpLibraryContent').value=id?(kind==='book'?row?.description:row?.content)||'':'';$('cpLibraryTitle').closest('label').hidden=kind==='link';$('cpLibraryTitle').required=kind!=='link';$('cpLibraryContentLabel').hidden=kind==='link';$('cpLibraryLinkFields').hidden=kind!=='link';$('cpLibraryPeople').hidden=kind!=='document';$('cpLibraryPeopleSearch').value='';$('cpLibraryPeople').querySelector('.cp-library-people').innerHTML=OCRecordPolicy.characters().map(char=>`<label><input type="checkbox" value="${esc(char.id)}" ${doc?.charIds?.includes(char.id)?'checked':''}>${esc(char.name)}</label>`).join('');$('cpLibraryResourceSearch').value='';resources();snapshot=formState();$('cpLibraryEditor').classList.add('active');(kind==='link'?$('cpLibraryResource'):$('cpLibraryTitle')).focus();}
function resources(){const kind=$('cpLibraryLinkKind').value,q=$('cpLibraryResourceSearch').value.trim().toLocaleLowerCase(),before=$('cpLibraryResource').value,rows=kind==='book'?books:documents;$('cpLibraryResource').innerHTML=rows.filter(row=>!q||String(row.title||'').toLocaleLowerCase().includes(q)).map(row=>`<option value="${esc(row.id)}">${esc(row.title)}${kind==='document'&&row.bookId?' · '+esc(books.find(b=>b.id===row.bookId)?.title||''):''}</option>`).join('');if([...$('cpLibraryResource').options].some(o=>o.value===before))$('cpLibraryResource').value=before;resourceVisibility();}
function resourceVisibility(){const book=$('cpLibraryLinkKind').value==='book',row=books.find(b=>b.id===$('cpLibraryResource').value);$('cpLibraryShowGlobal').closest('label').hidden=!book;if(book)$('cpLibraryShowGlobal').checked=!row?.hideFromDocuments;}
function formState(){return JSON.stringify([...$('cpLibraryEditor').querySelectorAll('input,textarea,select')].filter(el=>!el.id.endsWith('Search')).map(el=>el.type==='checkbox'?el.checked:el.value));}
function closeEditor(){const editor=$('cpLibraryEditor');if(!editor?.classList.contains('active'))return true;if(formState()!==snapshot&&!confirm('文庫尚未儲存，確定要放棄這次修改？'))return false;editor.classList.remove('active');return true;}
function saveEditor(event){event.preventDefault();if(!editing||!cp())return;const title=$('cpLibraryTitle').value.trim(),content=$('cpLibraryContent').value.trim();cp().library||={books:[],linkedBookIds:[]};cp().library.books||=[];cp().library.linkedBookIds||=[];const library=data();
if(editorKind==='link'){const kind=$('cpLibraryLinkKind').value,id=$('cpLibraryResource').value;if(!id)return;if(kind==='book'){if(!library.linkedBookIds.includes(id))library.linkedBookIds.push(id);const book=books.find(b=>b.id===id);if(book)book.hideFromDocuments=!$('cpLibraryShowGlobal').checked;selected='linked:'+id;renderDocumentsModule();}else{let book=ownBook();if(!book){book={id:uid('cpbook'),title:'關聯文檔',description:'',documents:[],linkedDocumentIds:[]};library.books.push(book);selected=book.id;}book.linkedDocumentIds||=[];if(!book.linkedDocumentIds.includes(id))book.linkedDocumentIds.push(id);}}
else if(editorKind==='book'){if(!title)return;const book=library.books.find(b=>b.id===editorId);if(book){book.title=title;book.description=content;}else{const row={id:uid('cpbook'),title,description:content,documents:[],linkedDocumentIds:[]};library.books.push(row);selected=row.id;}}
else{if(!title)return;const book=booksList().find(b=>b.key===selected),doc=chapters().find(d=>d.id===editorId),dormant=(doc?.charIds||[]).filter(id=>!OCRecordPolicy.character(id)),charIds=[...dormant,...$('cpLibraryPeople').querySelectorAll('input[type=checkbox]:checked')].map(el=>typeof el==='string'?el:el.value);if(doc?.linked||book?.linked){let global=documents.find(d=>d.id===editorId);if(global)Object.assign(global,{title,content,charIds});else documents.push({id:uid('doc'),title,content,charIds,bookId:book.id,factionIds:[],tags:[]});renderDocumentsModule();}else{const target=ownBook();if(!target)return;target.documents||=[];const found=target.documents.find(d=>d.id===editorId);if(found)Object.assign(found,{title,content,charIds});else target.documents.push({id:uid('cpdoc'),title,content,charIds});}}
snapshot=formState();$('cpLibraryEditor').classList.remove('active');save();}
function read(id){const entries=chapters(),index=entries.findIndex(d=>d.id===id),doc=entries[index];if(!doc)return;readerId=id;palette();$('cpLibraryReaderIndex').textContent=String(index+1).padStart(2,'0')+' / '+entries.length;$('cpLibraryReaderTitle').textContent=doc.title;$('cpLibraryReaderContent').textContent=doc.content||'這一頁尚未寫下內容。';$('cpLibraryReaderPeople').textContent=(doc.charIds||[]).map(id=>OCRecordPolicy.character(id)?.name).filter(Boolean).join('、')||cp().name;$('cpLibraryReader').querySelector('[data-cpl=prev]').disabled=index===0;$('cpLibraryReader').querySelector('[data-cpl=next]').disabled=index===entries.length-1;$('cpLibraryReader').classList.add('active');$('cpLibraryReader').querySelector('.character-archive-reader-scroll').scrollTop=0;}
function closeReader(){$('cpLibraryReader')?.classList.remove('active');readerId='';}
function exportText(){let out='# '+cp().name+' · CP 文庫\n\n';for(const book of booksList()){const previous=selected;selected=book.key;out+='## '+book.title+'\n'+(book.description||'')+'\n\n';for(const doc of chapters())out+='### '+doc.title+'\n'+(doc.content||'')+'\n\n';selected=previous;}return out;}
function click(event){const button=event.target.closest('[data-cpl]');if(!button)return;const action=button.dataset.cpl,id=button.dataset.id;if(action==='close')return close();if(action==='close-editor')return closeEditor();if(action==='close-reader')return closeReader();if(action==='edit'){editing=!editing;return render();}if(action==='book'){selected=id;return render();}if(action==='read')return read(id);if(action==='prev'||action==='next'){const entries=chapters(),index=entries.findIndex(d=>d.id===readerId),next=entries[index+(action==='prev'?-1:1)];if(next)read(next.id);return;}if(!editing)return;if(action==='new-book')return openEditor('book');if(action==='edit-book')return openEditor('book',selected);if(action==='link')return openEditor('link');if(action==='new-document')return openEditor('document');if(action==='edit-document')return openEditor('document',id);if(action==='remove-book'){const book=booksList().find(b=>b.key===selected);if(!book||!confirm(book.linked?'解除書籍關聯？原始內容會保留。':'刪除這本書與其中的文檔？'))return;if(book.linked)data().linkedBookIds=data().linkedBookIds.filter(id=>id!==book.id);else data().books=data().books.filter(b=>b.id!==book.id);selected='';return save();}if(action==='remove-document'){const book=ownBook(),doc=chapters().find(d=>d.id===id);if(!book||!doc||!confirm(doc.linked?'解除文檔關聯？原始文檔會保留。':'刪除此文檔？'))return;if(doc.linked)book.linkedDocumentIds=book.linkedDocumentIds.filter(key=>key!==id);else book.documents=book.documents.filter(d=>d.id!==id);return save();}if(action==='export'){const url=URL.createObjectURL(new Blob(['\uFEFF',exportText()],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=cp().name.replace(/[\\/:*?"<>|]/g,'_')+'-CP文庫.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}}
document.addEventListener('keydown',event=>{if(event.key!=='Escape')return;if($('cpLibraryEditor')?.classList.contains('active'))closeEditor();else if($('cpLibraryReader')?.classList.contains('active'))closeReader();else if($('cpLibraryModal')?.classList.contains('active'))close();});
window.OCCpLibrary={open,close,render,read,closeReader,openEditor,saveEditor,exportText,activeCp:()=>cpId};
})();
