/* Story timelines, media gallery, persistent list preferences and editor recovery. */
(()=>{
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const uid=prefix=>`${prefix}_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
  const safeColor=value=>/^#[0-9a-f]{6}$/i.test(value||'')?value:'#9b7069';
  const save=()=>saveStateToLocalStorage();
  const byOrder=items=>[...items].sort((a,b)=>(Number(a.order)||0)-(Number(b.order)||0));
  let selectedTimelineId=localStorage.getItem('oc_selected_timeline')||'';
  let galleryCharId='';
  let dragEventId='';
  const imageUrls=new Map();
  const mediaDb=()=>new Promise((resolve,reject)=>{const request=indexedDB.open('oc-media-library',1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains('files'))request.result.createObjectStore('files');};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});
  async function localFileAction(mode,id,value){const db=await mediaDb();return new Promise((resolve,reject)=>{const tx=db.transaction('files',mode==='get'?'readonly':'readwrite'),store=tx.objectStore('files'),req=mode==='get'?store.get(id):mode==='delete'?store.delete(id):store.put(value,id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
  const imageItems=()=>mediaLibrary.filter(item=>item&&!item.kind||item?.kind==='gallery');
  const mediaSettings=()=>mediaLibrary.find(item=>item?.kind==='settings');
  function syncWorkerUrl(value){let row=mediaSettings();if(!row){row={id:'__oc_media_settings__',kind:'settings'};mediaLibrary.push(row);}row.workerUrl=value;}
  const worldDefaults={a:'#a56e79',b:'#686a9c'};
  function worldColors(timeline){const faction=factions.find(f=>f.id===timeline?.factionId)||factions.find(f=>f.name===timeline?.worldName);const theme=faction?.themeColor;return {a:safeColor(theme?.primary||timeline?.worldColorA||worldDefaults.a),b:safeColor(theme?.secondary||timeline?.worldColorB||worldDefaults.b)};}
  function peopleFor(event){return (event.charIds||[]).map(id=>characters.find(c=>c.id===id)).filter(Boolean);}
  function avatarStack(people){return `<div class="timeline-avatar-stack" aria-label="關聯人物：${esc(people.map(c=>c.name).join('、'))}">${people.slice(0,5).map(c=>`<span class="timeline-mini-avatar" title="${esc(c.name)}" style="--avatar-color:${safeColor(c.themeColor?.primary||worldDefaults.a)}">${esc(c.name.slice(0,1))}${c.avatar?`<img src="${esc(c.avatar)}" alt="" loading="lazy" onerror="this.remove()">`:''}</span>`).join('')}${people.length>5?`<span class="timeline-avatar-more">+${people.length-5}</span>`:''}</div>`;}

  function renderTimeline(){
    const canvas=$('timelineCanvas'); if(!canvas)return;
    const picker=$('timelineSelect');
    if(!timelines.some(item=>item.id===selectedTimelineId))selectedTimelineId=timelines[0]?.id||'';
    picker.innerHTML=timelines.map(item=>`<option value="${esc(item.id)}">${esc(item.name)}</option>`).join('');
    picker.value=selectedTimelineId;
    const charPicker=$('timelineCharFilter'),prior=charPicker.value,typed=($('timelineCharSearch')?.value||'').trim().toLocaleLowerCase();
    const available=characters.filter(c=>!c.isHidden);
    const exact=available.find(c=>c.name.toLocaleLowerCase()===typed);
    charPicker.innerHTML='<option value="">全部人物</option>'+available.filter(c=>!typed||c.name.toLocaleLowerCase().includes(typed)||c.id===prior).map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');
    charPicker.value=exact?.id||prior;
    const timeline=timelines.find(item=>item.id===selectedTimelineId);
    if(!timeline){canvas.innerHTML='<div class="timeline-welcome"><i class="fa-solid fa-wand-magic-sparkles"></i><h3>從第一條時間線開始</h3><p>為世界觀建立事件，再拖曳節點排出故事主線。</p><button class="btn btn-primary" onclick="OCFeatures.newTimeline()">新建時間線</button></div>';return;}
    const world=factions.find(f=>f.id===timeline.factionId)?.name||timeline.worldName||'獨立世界觀';
    const colors=worldColors(timeline);
    const selectedChar=charPicker.value;
    const events=byOrder(timeline.events||[]).filter(event=>selectedChar?(event.charIds||[]).includes(selectedChar):!typed||peopleFor(event).some(c=>c.name.toLocaleLowerCase().includes(typed)));
    canvas.innerHTML=`<div class="timeline-cover" style="--world-a:${colors.a};--world-b:${colors.b}"><small>STORY CHRONICLE · ${esc(world)}</small><h2>${esc(timeline.name)}</h2><p>${esc(timeline.description||'將故事中的轉折與相遇，依照自己的節奏排在這裡。')}</p><span>${events.length} 個事件</span></div><div class="timeline-rail" style="--world-a:${colors.a};--world-b:${colors.b}">${events.map((event,index)=>{
      const a=safeColor(event.colorA),b=safeColor(event.colorB),people=peopleFor(event);
      return `<div class="timeline-gap"><button onclick="OCFeatures.openEvent(null,${index})" title="在此處新增事件">＋</button></div><article class="timeline-node" draggable="true" tabindex="0" role="button" data-event-id="${esc(event.id)}" style="--event-a:${a};--event-b:${b}" onclick="OCFeatures.openEventDetail('${esc(event.id)}')" onkeydown="if(event.target===this&&(event.key==='Enter'||event.key===' ')){event.preventDefault();OCFeatures.openEventDetail('${esc(event.id)}')}"><div class="timeline-dot"></div><div class="timeline-node-card"><div class="timeline-node-top"><small>${esc(event.when||`事件 ${index+1}`)}</small><span class="timeline-node-actions"><button type="button" aria-label="事件上移" onclick="event.stopPropagation();OCFeatures.shiftEvent('${esc(event.id)}',-1)">↑</button><button type="button" aria-label="事件下移" onclick="event.stopPropagation();OCFeatures.shiftEvent('${esc(event.id)}',1)">↓</button><span class="timeline-drag" title="拖曳排列">⋮⋮</span></span></div><h3>${esc(event.title)}</h3>${event.summary?`<p>${esc(event.summary)}</p>`:''}<div class="timeline-node-bottom">${people.length?avatarStack(people):'<span class="timeline-no-people">尚未關聯人物</span>'}<button type="button" class="timeline-edit-button" onclick="event.stopPropagation();OCFeatures.openEvent('${esc(event.id)}')"><i class="fa-solid fa-pen"></i> 編輯</button></div><small class="timeline-open">閱讀事件始末 ↗</small></div></article>`;
    }).join('')}<div class="timeline-gap"><button onclick="OCFeatures.openEvent(null,${events.length})" title="在結尾新增事件">＋</button></div></div>`;
    canvas.querySelectorAll('.timeline-node').forEach(node=>{
      node.addEventListener('dragstart',event=>{dragEventId=node.dataset.eventId;event.dataTransfer.effectAllowed='move';node.classList.add('dragging');});
      node.addEventListener('dragend',()=>{dragEventId='';node.classList.remove('dragging');});
      node.addEventListener('dragover',event=>{event.preventDefault();node.classList.add('drop-target');});
      node.addEventListener('dragleave',()=>node.classList.remove('drop-target'));
      node.addEventListener('drop',event=>{event.preventDefault();event.stopPropagation();node.classList.remove('drop-target');moveEvent(dragEventId,node.dataset.eventId,event.clientY>node.getBoundingClientRect().top+node.offsetHeight/2);});
    });
  }
  function selectTimeline(id){selectedTimelineId=id;localStorage.setItem('oc_selected_timeline',id);renderTimeline();}
  function openTimelineSettings(item){$('timelineSettingsId').value=item?.id||'';$('timelineSettingsTitle').textContent=item?'編輯世界與時間線':'新建時間線';$('timelineSettingsName').value=item?.name||'';$('timelineSettingsWorld').value=item?.worldName||factions.find(f=>f.id===item?.factionId)?.name||'';$('timelineSettingsDescription').value=item?.description||'';$('timelineWorldOptions').innerHTML=factions.map(f=>`<option value="${esc(f.name)}"></option>`).join('');const colors=worldColors(item);$('timelineWorldColorA').value=colors.a;$('timelineWorldColorB').value=colors.b;updateWorldColorPreview();$('timelineSettingsModal').classList.add('active');}
  function updateWorldColors(){const worldName=$('timelineSettingsWorld').value.trim(),faction=factions.find(f=>f.name===worldName),timeline=timelines.find(t=>t.worldName===worldName),colors=worldColors(faction?{factionId:faction.id}:timeline);$('timelineWorldColorA').value=colors.a;$('timelineWorldColorB').value=colors.b;updateWorldColorPreview();}
  function updateWorldColorPreview(){$('timelineWorldColorPreview').style.background=`linear-gradient(115deg,${safeColor($('timelineWorldColorA').value)},${safeColor($('timelineWorldColorB').value)})`;}
  function updateFactionColorPreview(){$('factionColorPreview').style.background=`linear-gradient(115deg,${safeColor($('factionColorA').value)},${safeColor($('factionColorB').value)})`;}
  function newTimeline(){openTimelineSettings(null);}
  function renameTimeline(){const item=timelines.find(t=>t.id===selectedTimelineId);if(item)openTimelineSettings(item);}
  function saveTimelineSettings(){const name=$('timelineSettingsName').value.trim();if(!name)return alert('請輸入時間線名稱。');const worldName=$('timelineSettingsWorld').value.trim(),colorA=safeColor($('timelineWorldColorA').value),colorB=safeColor($('timelineWorldColorB').value),faction=factions.find(f=>f.name===worldName);let item=timelines.find(t=>t.id===$('timelineSettingsId').value);if(!item){item={id:uid('timeline'),events:[]};timelines.push(item);}item.name=name;item.worldName=worldName;item.factionId=faction?.id||'';item.description=$('timelineSettingsDescription').value.trim();item.worldColorA=colorA;item.worldColorB=colorB;if(faction)faction.themeColor={primary:colorA,secondary:colorB,mode:'gradient'};if(worldName)for(const sibling of timelines)if(sibling.worldName===worldName||faction&&sibling.factionId===faction.id){sibling.worldColorA=colorA;sibling.worldColorB=colorB;}save();closeModal('timelineSettingsModal',true);renderFactionList();selectTimeline(item.id);}
  function deleteTimeline(){const item=timelines.find(t=>t.id===selectedTimelineId);if(!item||!confirm(`刪除時間線「${item.name}」及全部事件？`))return;timelines=timelines.filter(t=>t.id!==item.id);selectedTimelineId=timelines[0]?.id||'';localStorage.setItem('oc_selected_timeline',selectedTimelineId);save();renderTimeline();}
  function addEventSection(title='',content=''){
    const row=document.createElement('div');row.className='timeline-section-row';
    row.innerHTML=`<input class="timeline-section-title" placeholder="小標題" value="${esc(title)}"><textarea class="timeline-section-content" rows="4" placeholder="撰寫事件詳情…">${esc(content)}</textarea><button type="button" class="btn btn-xs btn-danger" onclick="this.parentElement.remove()">移除段落</button>`;
    $('timelineEventSections').append(row);
  }
  function openEvent(id=null,position=null){
    const timeline=timelines.find(t=>t.id===selectedTimelineId);if(!timeline)return;
    const event=(timeline.events||[]).find(item=>item.id===id);
    $('timelineEventModal').dataset.position=position===null?'':String(position);
    $('timelineEventId').value=event?.id||'';
    $('timelineEventTitle').value=event?.title||'';
    $('timelineEventWhen').value=event?.when||'';
    $('timelineEventSummary').value=event?.summary||'';
    $('timelineEventStory').value=event?.story||'';
    $('timelineEventCharSearch').value='';
    $('timelineColorA').value=safeColor(event?.colorA||'#bf806d');
    $('timelineColorB').value=safeColor(event?.colorB||'#6f629b');
    $('timelineEventChars').innerHTML=characters.filter(c=>!c.isHidden||(event?.charIds||[]).includes(c.id)).map(c=>`<label class="checkbox-pill"><input type="checkbox" value="${esc(c.id)}" ${(event?.charIds||[]).includes(c.id)?'checked':''}><span>${esc(c.name)}</span></label>`).join('');
    $('timelineEventSections').replaceChildren();(event?.sections||[]).forEach(section=>addEventSection(section.title,section.content));if(!event)addEventSection();
    $('timelineDeleteEvent').style.display=event?'':'none';$('timelineEventModal').classList.add('active');
  }
  function closeEvent(){ $('timelineEventModal').classList.remove('active'); }
  function saveEvent(){
    const timeline=timelines.find(t=>t.id===selectedTimelineId);if(!timeline)return;
    const title=$('timelineEventTitle').value.trim();if(!title)return alert('請輸入事件名稱。');
    timeline.events=timeline.events||[];
    const id=$('timelineEventId').value;let event=timeline.events.find(item=>item.id===id);
    if(!event){event={id:uid('event')};timeline.events.push(event);}
    event.title=title;event.when=$('timelineEventWhen').value.trim();event.summary=$('timelineEventSummary').value.trim();event.story=$('timelineEventStory').value.trim();event.colorA=$('timelineColorA').value;event.colorB=$('timelineColorB').value;
    event.charIds=[...$('timelineEventChars').querySelectorAll('input:checked')].map(input=>input.value);
    event.sections=[...$('timelineEventSections').children].map(row=>({title:row.querySelector('.timeline-section-title').value.trim(),content:row.querySelector('.timeline-section-content').value.trim()})).filter(s=>s.title||s.content);
    if(!id){const ordered=byOrder(timeline.events.filter(item=>item.id!==event.id));const rawPos=$('timelineEventModal').dataset.position;const pos=rawPos===''?ordered.length:Number(rawPos);ordered.splice(Number.isFinite(pos)?Math.max(0,Math.min(pos,ordered.length)):ordered.length,0,event);ordered.forEach((item,index)=>item.order=index+1);}
    save();closeEvent();renderTimeline();
  }
  function deleteEvent(){const timeline=timelines.find(t=>t.id===selectedTimelineId),id=$('timelineEventId').value;if(!timeline||!id||!confirm('刪除此事件？'))return;timeline.events=timeline.events.filter(item=>item.id!==id);save();closeEvent();renderTimeline();}
  function openEventDetail(id){const timeline=timelines.find(t=>t.id===selectedTimelineId),event=timeline?.events?.find(item=>item.id===id);if(!event)return;const people=peopleFor(event);$('timelineReadHero').style.setProperty('--world-a',safeColor(event.colorA||'#bf806d'));$('timelineReadHero').style.setProperty('--world-b',safeColor(event.colorB||'#6f629b'));$('timelineReadWorld').textContent=factions.find(f=>f.id===timeline.factionId)?.name||timeline.worldName||timeline.name;$('timelineReadWhen').textContent=event.when||'時間未標記';$('timelineReadTitle').textContent=event.title;$('timelineReadPeople').innerHTML=people.map(c=>`<span class="timeline-read-person"><img src="${esc(c.avatar||'')}" alt="" onerror="this.style.display='none'"><span>${esc(c.name)}</span></span>`).join('');$('timelineReadSummary').textContent=event.summary||'';$('timelineReadSummary').hidden=!event.summary;$('timelineReadStory').textContent=event.story||'尚未填寫事件始末。';$('timelineReadSections').innerHTML=(event.sections||[]).map(section=>`<section class="timeline-read-section"><h3>${esc(section.title||'補充')}</h3><div class="timeline-read-text">${esc(section.content||'')}</div></section>`).join('');$('timelineReadEditBtn').onclick=()=>{closeEventDetail();openEvent(id);};$('timelineReadModal').classList.add('active');}
  function closeEventDetail(){$('timelineReadModal').classList.remove('active');}
  function moveEvent(id,targetId,after){if(!id||id===targetId)return;const timeline=timelines.find(t=>t.id===selectedTimelineId);const ordered=byOrder(timeline.events),from=ordered.findIndex(item=>item.id===id);if(from<0)return;const [item]=ordered.splice(from,1);const target=ordered.findIndex(node=>node.id===targetId);ordered.splice(target+(after?1:0),0,item);ordered.forEach((node,index)=>node.order=index+1);save();renderTimeline();}
  function shiftEvent(id,direction){const timeline=timelines.find(t=>t.id===selectedTimelineId);if(!timeline)return;const ordered=byOrder(timeline.events),index=ordered.findIndex(item=>item.id===id),other=index+direction;if(index<0||other<0||other>=ordered.length)return;[ordered[index],ordered[other]]=[ordered[other],ordered[index]];ordered.forEach((item,position)=>item.order=position+1);save();renderTimeline();}
  function timelineText(oneId=null){return timelines.filter(t=>!oneId||t.id===oneId).map(t=>`# ${t.name}\n世界觀：${t.worldName||factions.find(f=>f.id===t.factionId)?.name||'未設定'}\n${t.description||''}\n\n`+byOrder(t.events||[]).map((event,index)=>`## ${index+1}. ${event.title}${event.when?`｜${event.when}`:''}\n${event.summary||''}\n關聯人物：${(event.charIds||[]).map(id=>characters.find(c=>c.id===id)?.name).filter(Boolean).join('、')||'無'}\n${event.story?`\n### 事件始末\n${event.story}\n`:''}`+(event.sections||[]).map(s=>`\n### ${s.title}\n${s.content}`).join('')+'\n').join('\n')).join('\n\n');}
  function openTimelineExportPreview(){const t=timelines.find(item=>item.id===selectedTimelineId);if(!t)return;$('timelineExportPreview').value=timelineText(t.id);$('timelineExportModal').classList.add('active');}
  async function copyTimelineText(){const value=$('timelineExportPreview').value;try{await navigator.clipboard.writeText(value);}catch{$('timelineExportPreview').select();document.execCommand('copy');}const button=$('timelineExportModal').querySelector('.modal-footer .btn-outline');button.textContent='已複製';setTimeout(()=>{button.innerHTML='<i class="fa-solid fa-copy"></i> 複製內容';},1800);}
  function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
  function exportTimelineText(){const t=timelines.find(t=>t.id===selectedTimelineId);if(!t)return;download(`${t.name}.txt`,$('timelineExportModal').classList.contains('active')?$('timelineExportPreview').value:timelineText(t.id),'text/plain;charset=utf-8');}
  function exportTimelineHtml(){const t=timelines.find(t=>t.id===selectedTimelineId);if(!t)return;const world=worldColors(t);const cards=byOrder(t.events||[]).map(e=>`<article style="border-left:6px solid ${safeColor(e.colorA)};padding:18px 24px;margin:20px 0;background:linear-gradient(105deg,${safeColor(e.colorA)}22,${safeColor(e.colorB)}22);border-radius:16px"><small>${esc(e.when)}</small><h2>${esc(e.title)}</h2><p>${esc(e.summary)}</p><p>人物：${(e.charIds||[]).map(id=>esc(characters.find(c=>c.id===id)?.name)).filter(Boolean).join('、')}</p>${e.story?`<h3>事件始末</h3><p style="white-space:pre-wrap">${esc(e.story)}</p>`:''}${(e.sections||[]).map(s=>`<h3>${esc(s.title)}</h3><p style="white-space:pre-wrap">${esc(s.content)}</p>`).join('')}</article>`).join('');download(`${t.name}-視覺時間線.html`,`<!doctype html><html lang="zh-TW"><meta charset="utf-8"><title>${esc(t.name)}</title><style>body{max-width:850px;margin:48px auto;padding:0 24px;background:#17151d;color:#f4ede6;font:16px/1.75 system-ui}h1{font-size:42px;background:linear-gradient(110deg,${world.a},${world.b});padding:18px 24px;border-radius:16px}@media print{body{background:white;color:#222}}</style><h1>${esc(t.name)}</h1><p>${esc(t.description)}</p>${cards}</html>`,'text/html;charset=utf-8');}
  function filterChoices(inputId,listId){const query=($(inputId)?.value||'').trim().toLocaleLowerCase(),list=$(listId);if(!list)return;list.querySelectorAll('label').forEach(label=>{label.hidden=!!query&&!label.textContent.toLocaleLowerCase().includes(query);});}

  const filterIds=['searchInput','tagFilter','characterSort','docSearchInput','docCharSearch','docCharFilter','docFactionFilter','docTagFilter','docSort','cpTypeFilter','timelineCharSearch','timelineCharFilter'];
  function rememberFilters(){const values=Object.fromEntries(filterIds.map(id=>[id,$(id)?.value||'']));localStorage.setItem('oc_list_preferences_v1',JSON.stringify(values));}
  function restoreFilters(){let values={};try{values=JSON.parse(localStorage.getItem('oc_list_preferences_v1')||'{}');}catch{}for(const id of filterIds){const field=$(id);if(field?.tagName!=='SELECT'&&values[id]!==undefined)field.value=values[id];}renderDocumentsModule();renderTimeline();for(const id of filterIds){const field=$(id);if(field?.tagName==='SELECT'&&values[id]!==undefined&&[...field.options].some(o=>o.value===values[id]))field.value=values[id];}renderCharacterCards();renderDocumentsModule();renderCpModule();renderTimeline();}

  const draftModals={characterModal:{id:'charId'},newCharWizardModal:{id:null},cpModal:{id:'cpId'},documentModal:{id:'docId'},bookModal:{id:'bookId'},factionModal:{id:'factionId'},paroModal:{id:'paroId'},visualNovelEditorModal:{id:'vnDocumentId'}};
  const dynamicIds={characterModal:['charCustomFieldsContainer'],newCharWizardModal:[],cpModal:['cpCustomSectionsContainer','cpMemberDetailsContainer'],documentModal:[],bookModal:[],factionModal:['factionCustomSectionsContainer'],paroModal:['paroFieldsContainer'],visualNovelEditorModal:[]};
  const draftTimers=new Map();const activeDraftKeys=new Map();
  let autoRestoreKey='';
  let draftDbPromise;
  function draftDb(){if(!draftDbPromise)draftDbPromise=new Promise((resolve,reject)=>{const request=indexedDB.open('oc-editor-drafts',1);request.onupgradeneeded=()=>request.result.createObjectStore('drafts');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});return draftDbPromise;}
  async function draftAction(mode,key,value){try{const db=await draftDb();return await new Promise((resolve,reject)=>{const tx=db.transaction('drafts',mode==='get'?'readonly':'readwrite'),store=tx.objectStore('drafts'),req=mode==='get'?store.get(key):mode==='delete'?store.delete(key):store.put(value,key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}catch(error){console.warn('草稿儲存失敗',error);return null;}}
  function draftKey(modalId){const config=draftModals[modalId];return `${modalId}:${config?.id?($(config.id)?.value||'new'):'new'}`;}
  function collectDraft(modalId){const root=$(modalId);if(!root)return null;const fields=[...root.querySelectorAll('input,textarea,select')].filter(el=>el.type!=='file');return {savedAt:Date.now(),dynamic:Object.fromEntries((dynamicIds[modalId]||[]).filter(id=>$(id)).map(id=>[id,$(id).innerHTML])),fields:fields.map(el=>({value:el.value,checked:el.checked}))};}
  function restoreDraft(modalId,draft){for(const [id,html] of Object.entries(draft.dynamic||{}))if($(id))$(id).innerHTML=html;const fields=[...$(modalId).querySelectorAll('input,textarea,select')].filter(el=>el.type!=='file');draft.fields.forEach((value,index)=>{if(!fields[index])return;fields[index].value=value.value;if(fields[index].type==='checkbox'||fields[index].type==='radio')fields[index].checked=value.checked;});}
  async function openDraft(modalId){const key=draftKey(modalId);activeDraftKeys.set(modalId,key);const draft=await draftAction('get',key);if(draft&&$(modalId)?.classList.contains('active')){let dismissed={};try{dismissed=JSON.parse(localStorage.getItem('oc_draft_dismissed_v1')||'{}');}catch{}if(key===autoRestoreKey){autoRestoreKey='';restoreDraft(modalId,draft);}else if(draft.savedAt<=Number(dismissed[key]||0))return;else if(confirm(`找到 ${new Date(draft.savedAt).toLocaleString()} 的未完成草稿。要恢復內容嗎？`))restoreDraft(modalId,draft);else await draftAction('delete',key);}}
  async function promptRecentDraft(){try{const db=await draftDb(),entries=await new Promise((resolve,reject)=>{const tx=db.transaction('drafts','readonly'),store=tx.objectStore('drafts'),keys=store.getAllKeys(),values=store.getAll();tx.oncomplete=()=>resolve(keys.result.map((key,index)=>({key,value:values.result[index]})));tx.onerror=()=>reject(tx.error);});let dismissed={};try{dismissed=JSON.parse(localStorage.getItem('oc_draft_dismissed_v1')||'{}');}catch{}const latest=entries.filter(item=>item.value?.savedAt&&item.value.savedAt>Number(dismissed[item.key]||0)).sort((a,b)=>b.value.savedAt-a.value.savedAt)[0];if(!latest)return;const [modalId,id]=String(latest.key).split(':');const openers={characterModal:()=>openCharacterModal(id),newCharWizardModal:()=>openNewCharacterWizard(),cpModal:()=>openCpModal(id==='new'?null:id),documentModal:()=>openDocumentModal(id==='new'?null:id),bookModal:()=>openBookModal(id==='new'?null:id),factionModal:()=>openFactionModal(id==='new'?null:id),paroModal:()=>openParoModal(id==='new'?null:id),visualNovelEditorModal:()=>openVisualNovelEditor(id)};if(!openers[modalId])return;if(confirm(`找到 ${new Date(latest.value.savedAt).toLocaleString()} 的未完成草稿。現在恢復嗎？`)){autoRestoreKey=latest.key;openers[modalId]();}else{for(const item of entries)if(item.value?.savedAt)dismissed[item.key]=item.value.savedAt;localStorage.setItem('oc_draft_dismissed_v1',JSON.stringify(dismissed));}}catch(error){console.warn('無法讀取草稿索引',error);}}
  function queueDraft(modalId){if(!activeDraftKeys.has(modalId))return;const badge=$(modalId)?.querySelector('.draft-status');if(badge)badge.textContent='草稿儲存中…';clearTimeout(draftTimers.get(modalId));draftTimers.set(modalId,setTimeout(()=>flushDraft(modalId),350));}
  async function flushDraft(modalId){const key=activeDraftKeys.get(modalId);if(!key)return;const data=collectDraft(modalId);if(data){await draftAction('put',key,data);const badge=$(modalId)?.querySelector('.draft-status');if(badge)badge.textContent='草稿已自動保存';}}
  function clearDraft(modalId){clearTimeout(draftTimers.get(modalId));const key=activeDraftKeys.get(modalId);if(key)draftAction('delete',key);activeDraftKeys.delete(modalId);}
  function wrapOpen(name,modalId){const original=window[name];if(typeof original!=='function')return;window[name]=function(...args){const result=original.apply(this,args);if($(modalId)?.classList.contains('active'))openDraft(modalId);return result;};}
  function wrapSave(name,modalId){const original=window[name];if(typeof original!=='function')return;window[name]=function(...args){const result=original.apply(this,args);if(!$(modalId)?.classList.contains('active'))clearDraft(modalId);return result;};}

  function galleryButton(charId){return `<button class="btn btn-xs btn-outline char-gallery-button" data-char-id="${esc(charId)}" onclick="OCFeatures.openGallery('${esc(charId)}')" title="編輯人物圖廊；左右滑動卡片可欣賞圖片"><i class="fa-solid fa-images"></i> 圖廊 <span>${imageItems().filter(m=>(m.charIds||[]).includes(charId)).length}</span><small>↔</small></button>`;}
  function openGallery(charId){galleryCharId=charId;const char=characters.find(c=>c.id===charId),modal=$('mediaGalleryModal');$('mediaGalleryTitle').textContent=`${char?.name||'人物'} · 圖廊`;modal.style.setProperty('--gallery-a',safeColor(char?.themeColor?.primary||worldDefaults.a));modal.style.setProperty('--gallery-b',safeColor(char?.themeColor?.secondary||worldDefaults.b));$('mediaUploadStatus').textContent='先存進此瀏覽器，備份人設卡時再同步到 R2。';modal.classList.add('active');renderGallery();}
  function closeGallery(){$('mediaGalleryModal').classList.remove('active');}
  function browseGallery(charId){galleryCharId=charId;const char=characters.find(c=>c.id===charId),modal=$('mediaBrowseModal');modal.style.setProperty('--gallery-a',safeColor(char?.themeColor?.primary||worldDefaults.a));modal.style.setProperty('--gallery-b',safeColor(char?.themeColor?.secondary||worldDefaults.b));$('mediaBrowseTitle').textContent=char?.name||'人物圖廊';const items=imageItems().filter(m=>(m.charIds||[]).includes(charId));$('mediaBrowseCount').textContent=`${items.length} 張圖片`;$('mediaBrowseMasonry').innerHTML=items.length?items.map(item=>`<button class="media-browse-tile" onclick="OCFeatures.viewImage('${esc(item.id)}')" aria-label="欣賞 ${esc(item.caption||'圖片')}"><img data-browse-id="${esc(item.id)}" alt="${esc(item.caption||'人物圖片')}"></button>`).join(''):'<div class="empty-state">這位人物還沒有圖片。可從人物卡的「圖廊」加入。</div>';modal.classList.add('active');items.forEach(async item=>{const image=modal.querySelector(`img[data-browse-id="${CSS.escape(item.id)}"]`);try{const url=await mediaSource(item);if(image?.isConnected)image.src=url;}catch(error){if(image?.isConnected)image.alt=error.message;}});}
  function closeBrowseGallery(){$('mediaBrowseModal').classList.remove('active');}
  function galleryPreviewHtml(char){const items=imageItems().filter(item=>(item.charIds||[]).includes(char.id));return `<div class="char-gallery-preview" style="--gallery-a:${safeColor(char.themeColor?.primary||worldDefaults.a)};--gallery-b:${safeColor(char.themeColor?.secondary||worldDefaults.b)}"><div class="char-gallery-preview-head"><strong>${esc(char.name)} · 圖廊</strong><small>左右滑動返回人設卡</small></div><div class="char-gallery-preview-grid${items.length?'':' is-empty'}">${items.length?items.map(item=>`<button class="char-gallery-preview-tile" onclick="OCFeatures.viewImage('${esc(item.id)}')" aria-label="放大 ${esc(item.caption||'圖片')}"><img data-card-image="${esc(item.id)}" alt="${esc(item.caption||'人物圖片')}"></button>`).join(''):`<div class="char-gallery-empty"><i class="fa-regular fa-images"></i><strong>尚未加入圖片</strong><span>滑回人設卡，點擊「圖廊」即可上傳。</span></div>`}</div></div>`;}
  function cpGalleryPreviewHtml(cp){const ids=[...new Set((cp.members||[]).map(member=>member.charId).filter(Boolean))],items=imageItems().filter(item=>{const linked=[...new Set(item.charIds||[])];return ids.length>0&&linked.length===ids.length&&linked.every(id=>ids.includes(id));});if(!items.length)return '';return `<div class="cp-gallery-preview"><div class="cp-gallery-head"><small>RELATIONSHIP GALLERY</small><strong>${esc(cp.name||'關係圖廊')}</strong><span>左滑返回關係卡</span></div><div class="cp-gallery-grid">${items.map(item=>`<button class="cp-gallery-tile" onclick="OCFeatures.viewImage('${esc(item.id)}')" aria-label="放大 ${esc(item.caption||'圖片')}"><img data-cp-image="${esc(item.id)}" alt="${esc(item.caption||'關係圖片')}"></button>`).join('')}</div></div>`;}
  let suppressCardClickUntil=0;
  function flipCard(card){if(!card||card.classList.contains('is-turning'))return;const showingGallery=!card.classList.contains('is-gallery');if(showingGallery)card.style.height=`${card.getBoundingClientRect().height}px`;suppressCardClickUntil=Date.now()+650;card.classList.add('is-turning');setTimeout(()=>{card.classList.toggle('is-gallery');if(showingGallery)card.querySelectorAll('img[data-card-image]').forEach(async img=>{const item=imageItems().find(row=>row.id===img.dataset.cardImage);if(item)try{img.src=await mediaSource(item);}catch(error){img.alt=error.message;}});},180);setTimeout(()=>{card.classList.remove('is-turning');if(!showingGallery)card.style.removeProperty('height');},430);}
  function flipCpCard(card){if(!card?.querySelector('.cp-gallery-preview')||card.classList.contains('is-turning'))return;const showingGallery=!card.classList.contains('is-gallery');if(showingGallery)card.style.height=`${card.getBoundingClientRect().height}px`;suppressCardClickUntil=Date.now()+650;card.classList.add('is-turning');setTimeout(()=>{card.classList.toggle('is-gallery');if(showingGallery)card.querySelectorAll('img[data-cp-image]').forEach(async img=>{const item=imageItems().find(row=>row.id===img.dataset.cpImage);if(item)try{img.src=await mediaSource(item);}catch(error){img.alt=error.message;}});},180);setTimeout(()=>{card.classList.remove('is-turning');if(!showingGallery)card.style.removeProperty('height');},430);}
  let viewedImageId='',imageZoom=1,imagePan={x:0,y:0},imagePointer=null;
  async function viewImage(id){const item=imageItems().find(m=>m.id===id);if(!item)return;viewedImageId=id;const img=$('mediaViewerImage');img.removeAttribute('src');$('mediaViewerCaption').textContent=item.caption||'人物圖片';$('mediaViewerModal').classList.add('active');resetImageZoom();try{img.src=await mediaSource(item);}catch(error){$('mediaViewerCaption').textContent=error.message;}}
  function closeImageViewer(){$('mediaViewerModal').classList.remove('active');viewedImageId='';}
  function applyImageZoom(){imageZoom=Math.max(1,Math.min(5,imageZoom));$('mediaViewerImage').style.transform=`translate(${imagePan.x}px,${imagePan.y}px) scale(${imageZoom})`;$('mediaViewerZoom').textContent=`${Math.round(imageZoom*100)}%`;}
  function zoomImage(delta){imageZoom+=delta>0?.25:-.25;if(imageZoom<=1)imagePan={x:0,y:0};applyImageZoom();}
  function resetImageZoom(){imageZoom=1;imagePan={x:0,y:0};applyImageZoom();}
  async function downloadViewedImage(){const item=imageItems().find(m=>m.id===viewedImageId);if(!item)return;try{const url=await mediaSource(item),link=document.createElement('a');link.href=url;link.download=item.caption||`圖片-${item.id}`;link.click();}catch(error){alert(error.message);}}
  function token(){try{return JSON.parse(localStorage.getItem('oc_cloud_auth_v1')||'null')?.access_token||'';}catch{return '';}}
  function workerUrl(){return (localStorage.getItem('oc_r2_worker_url')||mediaSettings()?.workerUrl||'https://oc-image-library.3dbatataro4.workers.dev').replace(/\/$/,'');}
  async function mediaRequest(path,options={}){const url=workerUrl(),jwt=token();if(!url)throw new Error('請先設定 R2 圖片服務網址。');if(!jwt)throw new Error('請先從備份中心登入雲端帳號。');const response=await fetch(url+path,{...options,headers:{...(options.headers||{}),Authorization:`Bearer ${jwt}`}});if(!response.ok){let message='圖片服務發生錯誤。';try{message=(await response.json()).error||message;}catch{}throw new Error(message);}return response;}
  async function mediaSource(item){if(item.url)return item.url;if(imageUrls.has(item.id))return imageUrls.get(item.id);let blob=await localFileAction('get',item.id);if(!blob){const response=await mediaRequest(`/media/${encodeURIComponent(item.id)}`);blob=await response.blob();}const url=URL.createObjectURL(blob);imageUrls.set(item.id,url);return url;}
  function hydrateAssetImages(root=document){const images=[];if(root.nodeType===1&&root.matches?.('img[src^="asset:"]'))images.push(root);root.querySelectorAll?.('img[src^="asset:"]').forEach(img=>images.push(img));for(const img of images){const ref=img.getAttribute('src'),id=ref?.slice(6),item=mediaLibrary.find(row=>row.id===id);if(!item)continue;img.removeAttribute('onerror');img.removeAttribute('src');mediaSource(item).then(url=>{if(img.isConnected&&(!img.getAttribute('src')||img.dataset.assetRef===ref))img.src=url;}).catch(()=>{img.alt='圖片暫時無法載入';});img.dataset.assetRef=ref;}}
  function updateMediaFileSelection(){const files=$('mediaUploadInput')?.files;$('mediaFileSelection').textContent=files?.length?`已選擇 ${files.length} 張圖片`:'尚未選擇圖片';}
  function renderGallery(){updateMediaFileSelection();const items=imageItems().filter(m=>(m.charIds||[]).includes(galleryCharId));$('mediaMasonry').innerHTML=items.length?items.map(item=>`<div class="media-tile"><img data-media-id="${esc(item.id)}" alt="${esc(item.caption||'人物圖片')}"><div><span>${esc(item.caption||'未命名圖片')}</span><button class="btn btn-xs btn-outline" onclick="OCFeatures.editImage('${esc(item.id)}')">編輯</button></div></div>`).join(''):'<div class="empty-state">尚無圖片。選擇圖片後會先存入本機並立即預覽。</div>';items.forEach(async item=>{const img=$('mediaMasonry').querySelector(`img[data-media-id="${CSS.escape(item.id)}"]`);try{const url=await mediaSource(item);if(img?.isConnected)img.src=url;}catch(error){if(img?.isConnected)img.alt=error.message;}});}
  async function uploadImages(){const input=$('mediaUploadInput'),files=[...input.files],status=$('mediaUploadStatus');if(!files.length)return;try{for(const file of files){if(!/^image\/(png|jpeg|webp|gif|avif)$/i.test(file.type))throw new Error(`${file.name} 格式不支援，請使用 PNG、JPEG、WebP、GIF 或 AVIF。`);if(file.size>20*1024*1024)throw new Error(`${file.name} 超過 20 MB。`);}for(let i=0;i<files.length;i++){const file=files[i],key=uid('image');status.textContent=`儲存到本機 ${i+1}/${files.length}：${file.name}`;await localFileAction('put',key,file);mediaLibrary.push({id:key,caption:file.name,charIds:[galleryCharId],type:file.type,size:file.size,createdAt:Date.now(),localOnly:true});}save();input.value='';status.textContent=`已加入本機圖庫 ${files.length} 張，可立即預覽；備份人設卡時可批次同步 R2。`;renderGallery();renderCharacterCards();renderCpModule();}catch(error){status.textContent=error.name==='QuotaExceededError'?'本機儲存空間不足，請改用較小圖片或稍後清理瀏覽器資料。':error.message;}}
  function editImage(id){const item=mediaLibrary.find(m=>m.id===id);if(!item)return;$('mediaEditId').value=id;$('mediaCaption').value=item.caption||'';$('mediaEditChars').innerHTML=characters.map(c=>`<label class="checkbox-pill"><input type="checkbox" value="${esc(c.id)}" ${(item.charIds||[]).includes(c.id)?'checked':''}><span>${esc(c.name)}</span></label>`).join('');$('mediaEditModal').classList.add('active');}
  function saveImage(){const item=mediaLibrary.find(m=>m.id===$('mediaEditId').value);if(!item)return;item.caption=$('mediaCaption').value.trim();item.charIds=[...$('mediaEditChars').querySelectorAll('input:checked')].map(input=>input.value);save();closeModal('mediaEditModal',true);renderGallery();renderCharacterCards();renderCpModule();}
  async function deleteImage(){const item=imageItems().find(m=>m.id===$('mediaEditId').value);if(!item||!confirm(`從人物圖庫刪除此圖片？${item.localOnly?'尚未備份的本機圖片會直接移除。':'已同步至 R2 的圖片也會一併刪除。'}`))return;try{if(!item.localOnly)await mediaRequest(`/media/${encodeURIComponent(item.id)}`,{method:'DELETE'});await localFileAction('delete',item.id);mediaLibrary=mediaLibrary.filter(m=>m.id!==item.id);const url=imageUrls.get(item.id);if(url?.startsWith('blob:'))URL.revokeObjectURL(url);imageUrls.delete(item.id);save();closeModal('mediaEditModal',true);renderGallery();renderCharacterCards();renderCpModule();}catch(error){alert(error.message);}}
  function openMediaSettings(){openApiKeyModal();}
  function populateApiSettings(){$('mediaWorkerUrl').value=workerUrl();}
  function saveApiSettings(){const value=$('mediaWorkerUrl').value.trim().replace(/\/$/,'');if(value&&!/^https:\/\//i.test(value))return false;localStorage.setItem('oc_r2_worker_url',value);syncWorkerUrl(value);save();return true;}
  function saveMediaSettings(){const value=$('mediaWorkerUrl').value.trim().replace(/\/$/,'');if(value&&!/^https:\/\//i.test(value))return alert('請輸入 HTTPS 網址。');localStorage.setItem('oc_r2_worker_url',value);syncWorkerUrl(value);save();closeModal('mediaSettingsModal',true);}
  async function uploadPendingMedia(){const pending=mediaLibrary.filter(item=>item?.localOnly&&!item.url);if(!pending.length)return [];if(!workerUrl())throw new Error('尚有本機素材待同步。請先在 API 設定填入 R2 Worker 網址。');if(!token())throw new Error('尚有本機素材待同步。請先登入雲端帳號，再執行雲端備份。');for(let i=0;i<pending.length;i++){const item=pending[i],blob=await localFileAction('get',item.id);if(!blob)throw new Error(`本機素材「${item.title||item.caption||item.id}」找不到，請重新選取。`);$('mediaUploadStatus').textContent=`備份前同步素材至 R2 ${i+1}/${pending.length}`;await mediaRequest(`/media/${encodeURIComponent(item.id)}`,{method:'PUT',headers:{'Content-Type':item.type||blob.type||'image/jpeg'},body:blob});}$('mediaUploadStatus').textContent=`已同步 ${pending.length} 個素材至 R2。`;return pending.map(item=>item.id);}
  function restoreMediaSettingsFromData(){const value=mediaSettings()?.workerUrl;if(typeof value==='string'){localStorage.setItem('oc_r2_worker_url',value);}}

  function install(){
    const assetObserver=new MutationObserver(records=>{for(const record of records){if(record.type==='attributes')hydrateAssetImages(record.target);else record.addedNodes.forEach(node=>{if(node.nodeType===1)hydrateAssetImages(node);});}});assetObserver.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:['src']});hydrateAssetImages();
    if(workerUrl()&&!mediaSettings()){syncWorkerUrl(workerUrl());save();}
    filterIds.forEach(id=>$(id)?.addEventListener('input',rememberFilters));
    filterIds.forEach(id=>$(id)?.addEventListener('change',rememberFilters));
    for(const modalId of Object.keys(draftModals)){
      const header=$(modalId)?.querySelector('.modal-header');if(header){const badge=document.createElement('small');badge.className='draft-status';badge.textContent='';header.append(badge);}
      $(modalId)?.addEventListener('input',()=>queueDraft(modalId));
      $(modalId)?.addEventListener('change',()=>queueDraft(modalId));
    }
    window.addEventListener('pagehide',()=>{for(const modalId of activeDraftKeys.keys())flushDraft(modalId);});
    document.addEventListener('visibilitychange',()=>{if(document.hidden)for(const modalId of activeDraftKeys.keys())flushDraft(modalId);});
    [['openCharacterModal','characterModal'],['openNewCharacterWizard','newCharWizardModal'],['openCpModal','cpModal'],['openDocumentModal','documentModal'],['openBookModal','bookModal'],['openFactionModal','factionModal'],['openParoModal','paroModal'],['openVisualNovelEditor','visualNovelEditorModal']].forEach(([name,modal])=>wrapOpen(name,modal));
    [['saveCharacterForm','characterModal'],['finishWizard','newCharWizardModal'],['saveCpForm','cpModal'],['saveDocumentForm','documentModal'],['saveBookForm','bookModal'],['saveFactionForm','factionModal'],['saveParoForm','paroModal'],['saveVisualNovelScript','visualNovelEditorModal']].forEach(([name,modal])=>wrapSave(name,modal));
    const oldClose=window.closeModal;window.closeModal=function(modalId,force=false){const result=oldClose(modalId,force);if(result&&!force&&draftModals[modalId])clearDraft(modalId);return result;};
    const oldCard=window.createCharacterCardHtml;window.createCharacterCardHtml=function(char){let html=oldCard(char).replace('<div class="char-card-body">',galleryButton(char.id)+'<div class="char-card-body">');const end=html.lastIndexOf('</div>');return end<0?html:html.slice(0,end)+galleryPreviewHtml(char)+html.slice(end);};
    document.addEventListener('click',event=>{if(Date.now()<suppressCardClickUntil&&event.target.closest('.char-card,.cp-card')){event.preventDefault();event.stopImmediatePropagation();}},true);
    let touch=null;document.addEventListener('touchstart',event=>{const card=event.target.closest('.char-card'),control=event.target.closest('button,a,input,textarea');touch=card&&(!control||control.closest('.char-gallery-preview-tile'))?{x:event.touches[0].clientX,y:event.touches[0].clientY,card}:null;},{passive:true});
    document.addEventListener('touchend',event=>{if(!touch)return;const dx=event.changedTouches[0].clientX-touch.x,dy=event.changedTouches[0].clientY-touch.y;if(Math.abs(dx)>75&&Math.abs(dx)>Math.abs(dy)*1.3&&touch.card)flipCard(touch.card);touch=null;},{passive:true});
    let pointer=null;document.addEventListener('pointerdown',event=>{const control=event.target.closest('button,a,input,textarea');if(event.pointerType!=='mouse'||event.button!==0||(control&&!control.closest('.char-gallery-preview-tile')))return;const card=event.target.closest('.char-card');pointer=card?{x:event.clientX,y:event.clientY,card}:null;});
    document.addEventListener('pointerup',event=>{if(!pointer)return;const dx=event.clientX-pointer.x,dy=event.clientY-pointer.y;if(Math.abs(dx)>75&&Math.abs(dx)>Math.abs(dy)*1.3&&pointer.card)flipCard(pointer.card);pointer=null;});
    let cpTouch=null;document.addEventListener('touchstart',event=>{const card=event.target.closest('.cp-card'),control=event.target.closest('button,a,input,textarea');cpTouch=card?.querySelector('.cp-gallery-preview')&&(!control||control.closest('.cp-gallery-tile'))?{x:event.touches[0].clientX,y:event.touches[0].clientY,card}:null;},{passive:true});
    document.addEventListener('touchend',event=>{if(!cpTouch)return;const dx=event.changedTouches[0].clientX-cpTouch.x,dy=event.changedTouches[0].clientY-cpTouch.y,open=!cpTouch.card.classList.contains('is-gallery');if(Math.abs(dx)>75&&Math.abs(dx)>Math.abs(dy)*1.3&&(open?dx>0:dx<0))flipCpCard(cpTouch.card);cpTouch=null;},{passive:true});
    let cpPointer=null;document.addEventListener('pointerdown',event=>{const card=event.target.closest('.cp-card'),control=event.target.closest('button,a,input,textarea');cpPointer=event.pointerType==='mouse'&&event.button===0&&card?.querySelector('.cp-gallery-preview')&&(!control||control.closest('.cp-gallery-tile'))?{x:event.clientX,y:event.clientY,card}:null;});
    document.addEventListener('pointerup',event=>{if(!cpPointer)return;const dx=event.clientX-cpPointer.x,dy=event.clientY-cpPointer.y,open=!cpPointer.card.classList.contains('is-gallery');if(Math.abs(dx)>75&&Math.abs(dx)>Math.abs(dy)*1.3&&(open?dx>0:dx<0))flipCpCard(cpPointer.card);cpPointer=null;});
    $('mediaViewerStage')?.addEventListener('wheel',event=>{if(!$('mediaViewerModal').classList.contains('active'))return;event.preventDefault();zoomImage(event.deltaY<0?1:-1);},{passive:false});
    $('mediaViewerStage')?.addEventListener('pointerdown',event=>{if(imageZoom<=1)return;imagePointer={x:event.clientX,y:event.clientY,panX:imagePan.x,panY:imagePan.y};event.currentTarget.setPointerCapture(event.pointerId);});
    $('mediaViewerStage')?.addEventListener('pointermove',event=>{if(!imagePointer)return;imagePan={x:imagePointer.panX+event.clientX-imagePointer.x,y:imagePointer.panY+event.clientY-imagePointer.y};applyImageZoom();});
    $('mediaViewerStage')?.addEventListener('pointerup',()=>{imagePointer=null;});
    $('mediaViewerImage')?.addEventListener('dblclick',()=>{imageZoom=imageZoom===1?2:1;if(imageZoom===1)imagePan={x:0,y:0};applyImageZoom();});
    restoreFilters();renderTimeline();promptRecentDraft();
  }
  window.OCFeatures={renderAll(){renderTimeline();},renderTimeline,selectTimeline,newTimeline,renameTimeline,saveTimelineSettings,deleteTimeline,updateWorldColors,updateWorldColorPreview,updateFactionColorPreview,openEvent,closeEvent,openEventDetail,closeEventDetail,addEventSection,saveEvent,deleteEvent,shiftEvent,timelineText,openTimelineExportPreview,copyTimelineText,exportTimelineText,exportTimelineHtml,filterChoices,rememberFilters,openGallery,closeGallery,browseGallery,closeBrowseGallery,cpGalleryPreviewHtml,viewImage,closeImageViewer,zoomImage,resetImageZoom,downloadViewedImage,updateMediaFileSelection,uploadImages,editImage,saveImage,deleteImage,openMediaSettings,saveMediaSettings,populateApiSettings,saveApiSettings,uploadPendingMedia,restoreMediaSettingsFromData,storeFile:(id,file)=>localFileAction('put',id,file),readFile:id=>localFileAction('get',id),removeFile:id=>localFileAction('delete',id),deleteRemoteFile:id=>mediaRequest(`/media/${encodeURIComponent(id)}`,{method:'DELETE'}),source:mediaSource};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
