/* Shortest-column masonry inside a vertically scrolling viewport. */
(()=>{'use strict';
const selectors='.char-gallery-preview-grid,.cp-gallery-grid,.media-browse-masonry,.media-masonry',states=new WeakMap();
function schedule(state){if(state.pending)return;state.pending=true;requestAnimationFrame(()=>{state.pending=false;layout(state);});}
function layout(state){const {root,canvas}=state,width=canvas.clientWidth;if(!root.isConnected||width<1)return;const gap=12,count=root.matches('.char-gallery-preview-grid,.cp-gallery-grid')?2:Math.max(2,Math.min(4,Math.floor((width+gap)/190))),tileWidth=(width-gap*(count-1))/count,heights=Array(count).fill(0);for(const tile of canvas.children){tile.style.width=tileWidth+'px';const img=tile.querySelector('img'),loaded=img?.naturalWidth>0;if(img&&!loaded)img.style.aspectRatio='1';else if(img)img.style.removeProperty('aspect-ratio');const col=heights.indexOf(Math.min(...heights));tile.style.left=(col*(tileWidth+gap))+'px';tile.style.top=heights[col]+'px';heights[col]+=tile.getBoundingClientRect().height+gap;}canvas.style.height=Math.max(0,Math.max(...heights)-gap)+'px';root.dataset.masonryColumns=count;}
function mount(root){let state=states.get(root);if(!state){const canvas=document.createElement('div');canvas.className='gallery-masonry-canvas';state={root,canvas,pending:false};states.set(root,state);root.classList.add('has-gallery-masonry');root.addEventListener('load',()=>schedule(state),true);root.addEventListener('error',()=>schedule(state),true);new ResizeObserver(()=>schedule(state)).observe(root);}if(!state.canvas.isConnected){const tiles=[...root.children].filter(el=>el.matches('button,article,.media-tile'));if(!tiles.length)return;state.canvas.replaceChildren(...tiles);root.append(state.canvas);}schedule(state);}
let queued=false;function scan(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;document.querySelectorAll(selectors).forEach(mount);});}
new MutationObserver(records=>{if(records.some(record=>record.type==='childList'||record.type==='attributes'&&record.attributeName==='class'))scan();}).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});document.addEventListener('DOMContentLoaded',scan);window.OCGalleryMasonry={refresh:scan};
})();
