/* Reusable CG, BGM and SE library. Metadata follows the workshop backup; files use the shared IndexedDB/R2 store. */
(()=>{
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const types={cg:{name:'CG 圖片',accept:'image/png,image/jpeg,image/webp,image/gif,image/avif',icon:'fa-image',limit:20},bgm:{name:'BGM 音樂',accept:'audio/mpeg,audio/mp4,audio/ogg,audio/wav,audio/webm',icon:'fa-music',limit:50},se:{name:'SE 音效',accept:'audio/mpeg,audio/mp4,audio/ogg,audio/wav,audio/webm',icon:'fa-volume-high',limit:50}};
  let activeType='cg',tab='library',insertTarget='script',previewId='',holdTimer=null,held=false,previewAudio=null;
  const items=()=>mediaLibrary.filter(row=>row?.kind==='vn-asset'&&row.assetType===activeType&&row.listed!==false);
  const parseTags=value=>[...new Set(String(value||'').split(/[,，、]/).map(tag=>tag.trim()).filter(Boolean))].slice(0,12);
  const fileOk=(file,type)=>type==='cg'?/^image\/(png|jpeg|webp|gif|avif)$/i.test(file.type):/^audio\/(mpeg|mp4|ogg|wav|x-wav|webm)$/i.test(file.type);
  function open(type,target='script'){if(!types[type])return;activeType=type;insertTarget=target;previewId='';$('vnAssetTitle').textContent=`選擇 ${types[type].name}`;$('vnAssetFile').accept=types[type].accept;$('vnAssetSearch').value='';$('vnAssetTagFilter').value='';$('vnAssetUrl').value='';$('vnAssetSaveUrl').checked=false;$('vnAssetUrlTitle').value='';$('vnAssetUrlTags').value='';$('vnAssetFile').value='';$('vnAssetRememberFile').checked=false;$('vnAssetFileTitle').value='';$('vnAssetFileTags').value='';$('vnAssetStatus').textContent='';toggleSaveFields();toggleFileFields();showTab('library');$('vnAssetModal').classList.add('active');}
  function close(){closePreview();$('vnAssetModal').classList.remove('active');}
  function showTab(name){tab=name;for(const key of ['library','url','upload']){$(`vnAsset${key[0].toUpperCase()+key.slice(1)}Pane`).hidden=key!==name;$(`vnAssetTab${key[0].toUpperCase()+key.slice(1)}`).classList.toggle('active',key===name);}if(name==='library')render();if(name==='upload')renderInlineFiles();}
  function renderInlineFiles(){const docId=$('vnDocumentId')?.value,rows=mediaLibrary.filter(row=>row?.kind==='vn-asset'&&row.listed===false&&row.assetType===activeType&&row.docId===docId);$('vnAssetInlineFiles').innerHTML=rows.length?`<h4>本篇直接上傳</h4>${rows.map(row=>`<div class="vn-inline-file"><span title="${esc(row.title)}">${esc(row.title)}</span><button class="btn btn-xs btn-outline" onclick="OCVnAssets.preview('${esc(row.id)}')">預覽／管理</button><button class="btn btn-xs btn-primary" onclick="OCVnAssets.insert('${esc(row.id)}')">插入</button></div>`).join('')}`:'';}
  function render(){if(tab!=='library')return;const all=items(),tagSelect=$('vnAssetTagFilter'),oldTag=tagSelect.value,tags=[...new Set(all.flatMap(item=>item.tags||[]))].sort((a,b)=>a.localeCompare(b,'zh-Hant'));tagSelect.innerHTML='<option value="">所有標籤</option>'+tags.map(tag=>`<option value="${esc(tag)}">${esc(tag)}</option>`).join('');tagSelect.value=tags.includes(oldTag)?oldTag:'';const query=$('vnAssetSearch').value.trim().toLocaleLowerCase(),tag=tagSelect.value,shown=all.filter(item=>(!tag||(item.tags||[]).includes(tag))&&(!query||`${item.title||''} ${(item.tags||[]).join(' ')}`.toLocaleLowerCase().includes(query)));$('vnAssetGrid').innerHTML=shown.length?shown.map(item=>`<button class="vn-asset-card" data-id="${esc(item.id)}" onpointerdown="OCVnAssets.holdStart(event,'${esc(item.id)}')" onpointerup="OCVnAssets.holdEnd()" onpointercancel="OCVnAssets.holdEnd()" onpointerleave="OCVnAssets.holdEnd()" oncontextmenu="event.preventDefault();OCVnAssets.preview('${esc(item.id)}')" onclick="OCVnAssets.choose('${esc(item.id)}')"><span class="vn-asset-thumb">${activeType==='cg'?`<img data-asset-image="${esc(item.id)}" alt="">`:`<i class="fa-solid ${types[activeType].icon}"></i>`}</span><strong>${esc(item.title||'未命名素材')}</strong><span class="vn-asset-tags">${(item.tags||[]).map(t=>`<em>${esc(t)}</em>`).join('')}</span><small>按一下插入 · 長按預覽</small></button>`).join(''):'<div class="empty-state">尚無符合條件的素材。可上傳檔案或保存網址。</div>';if(activeType==='cg')shown.forEach(async item=>{try{const img=$('vnAssetGrid').querySelector(`img[data-asset-image="${CSS.escape(item.id)}"]`),url=await resolve(`asset:${item.id}`);if(img?.isConnected)img.src=url;}catch{}});}
  function holdStart(event,id){if(event.pointerType==='mouse'&&event.button!==0)return;held=false;clearTimeout(holdTimer);holdTimer=setTimeout(()=>{held=true;preview(id);},550);}
  function holdEnd(){clearTimeout(holdTimer);holdTimer=null;}
  function choose(id){if(held){held=false;return;}insert(id);}
  function insertCommand(value){if(insertTarget==='global'){const input=$('vnGlobalBgm');input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}));close();return;}const editor=$('vnScriptText');if(!editor)return;const command=`@${activeType} ${value}`,start=editor.selectionStart??editor.value.length,end=editor.selectionEnd??start,before=editor.value.slice(0,start),after=editor.value.slice(end),prefix=!before?'':before.endsWith('\n\n')?'':before.endsWith('\n')?'\n':'\n\n',suffix=!after?'':after.startsWith('\n\n')?'':after.startsWith('\n')?'\n':'\n\n';editor.setRangeText(`${prefix}${command}${suffix}`,start,end,'end');editor.focus();close();}
  function insert(id){const item=mediaLibrary.find(row=>row.id===id&&row.kind==='vn-asset');if(!item)return;insertCommand(item.url||`asset:${item.id}`);}
  function toggleSaveFields(){$('vnAssetUrlMeta').hidden=!$('vnAssetSaveUrl').checked;}
  function toggleFileFields(){$('vnAssetFileMeta').hidden=!$('vnAssetRememberFile').checked;}
  function urlChanged(){const url=$('vnAssetUrl').value.trim(),box=$('vnAssetUrlPreview');box.replaceChildren();if(!/^https?:\/\//i.test(url))return;if(activeType==='cg'){const img=document.createElement('img');img.src=url;img.alt='網址圖片預覽';box.append(img);}else{const audio=document.createElement('audio');audio.controls=true;audio.preload='none';audio.src=url;box.append(audio);}}
  function insertUrl(){const url=$('vnAssetUrl').value.trim();if(!/^https?:\/\//i.test(url)){alert('請輸入有效的 http(s) 素材網址。');return;}if($('vnAssetSaveUrl').checked){const title=$('vnAssetUrlTitle').value.trim()||`${types[activeType].name} ${items().length+1}`;mediaLibrary.push({id:`vna_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,kind:'vn-asset',assetType:activeType,title,tags:parseTags($('vnAssetUrlTags').value),url,createdAt:Date.now(),localOnly:false});saveStateToLocalStorage();}insertCommand(url);}
  function fileChanged(){const file=$('vnAssetFile').files?.[0];if(file&&!$('vnAssetFileTitle').value)$('vnAssetFileTitle').value=file.name.replace(/\.[^.]+$/,'');$('vnAssetStatus').textContent=file?`${file.name} · ${(file.size/1024/1024).toFixed(1)} MB`:'';}
  async function saveFile(){const file=$('vnAssetFile').files?.[0],status=$('vnAssetStatus');if(!file){status.textContent='請先選擇素材檔案。';return;}if(!fileOk(file,activeType)){status.textContent='不支援此檔案格式。請選擇圖片或常見音訊格式。';return;}if(file.size>types[activeType].limit*1024*1024){status.textContent=`檔案不可超過 ${types[activeType].limit} MB。`;return;}const id=`vna_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,listed=$('vnAssetRememberFile').checked;try{status.textContent='儲存本機素材…';await OCFeatures.storeFile(id,file);mediaLibrary.push({id,kind:'vn-asset',assetType:activeType,listed,docId:$('vnDocumentId')?.value||'',title:listed?$('vnAssetFileTitle').value.trim()||file.name:file.name,tags:listed?parseTags($('vnAssetFileTags').value):[],type:file.type,size:file.size,createdAt:Date.now(),localOnly:true});saveStateToLocalStorage();insertCommand(`asset:${id}`);}catch(error){status.textContent=error.name==='QuotaExceededError'?'本機儲存空間不足。請先清理瀏覽器儲存空間。':error.message;}}
  async function resolve(value){const match=String(value||'').match(/^asset:([a-zA-Z0-9_-]+)$/);if(!match)return value;const item=mediaLibrary.find(row=>row.id===match[1]&&row.kind==='vn-asset');if(!item)throw new Error('素材已從素材庫移除。');return OCFeatures.source(item);}
  async function preview(id){const item=mediaLibrary.find(row=>row.id===id&&row.kind==='vn-asset');if(!item)return;previewId=id;$('vnAssetPreviewTitle').textContent=item.title||'素材預覽';const body=$('vnAssetPreviewBody');body.replaceChildren();const tags=document.createElement('p');tags.className='vn-asset-preview-tags';tags.textContent=(item.tags||[]).map(t=>`#${t}`).join('  ');try{const source=await resolve(item.url||`asset:${id}`);if(item.assetType==='cg'){const img=document.createElement('img');img.src=source;img.alt=item.title||'CG 預覽';body.append(img);}else{previewAudio=document.createElement('audio');previewAudio.controls=true;previewAudio.autoplay=true;previewAudio.src=source;body.append(previewAudio);}body.append(tags);}catch(error){body.textContent=error.message;}const actions=document.createElement('div');actions.className='vn-asset-manage';actions.innerHTML=`<button class="btn btn-xs btn-outline" onclick="OCVnAssets.editPreviewed()">編輯標題／標籤</button><button class="btn btn-xs btn-danger" onclick="OCVnAssets.deletePreviewed()">刪除素材</button>`;body.append(actions);$('vnAssetPreviewModal').classList.add('active');}
  function closePreview(){previewAudio?.pause();previewAudio=null;$('vnAssetPreviewModal').classList.remove('active');}
  function insertPreviewed(){if(previewId)insert(previewId);}
  function editPreviewed(){const item=mediaLibrary.find(row=>row.id===previewId);if(!item)return;const title=prompt('素材標題',item.title||'');if(title===null)return;const tags=prompt('獨立標籤（逗號分隔）',(item.tags||[]).join('、'));if(tags===null)return;item.title=title.trim()||item.title;item.tags=parseTags(tags);saveStateToLocalStorage();closePreview();render();}
  async function deletePreviewed(){const item=mediaLibrary.find(row=>row.id===previewId);if(!item||!confirm(`刪除素材「${item.title}」？劇本中已插入的素材代碼將無法播放。`))return;try{if(!item.url){if(!item.localOnly)await OCFeatures.deleteRemoteFile(item.id);await OCFeatures.removeFile(item.id);}mediaLibrary=mediaLibrary.filter(row=>row.id!==item.id);saveStateToLocalStorage();closePreview();render();renderInlineFiles();}catch(error){alert(error.message);}}
  window.OCVnAssets={open,close,showTab,render,holdStart,holdEnd,choose,insert,insertUrl,toggleSaveFields,toggleFileFields,urlChanged,fileChanged,saveFile,resolve,preview,closePreview,insertPreviewed,editPreviewed,deletePreviewed};
})();
