/* Reusable, draggable layouts for the advanced visual-novel reader. */
(()=>{
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const number=(value,min,max)=>Math.max(min,Math.min(max,Number(value)||0));
  const templates=()=>mediaLibrary.filter(row=>row?.kind==='vn-layout-template');
  const defaults=mode=>({
    dialogue:{x:mode==='portrait'?3:12,y:mode==='portrait'?65:72,w:mode==='portrait'?94:76,h:mode==='portrait'?22:25},
    name:{x:mode==='portrait'?7:17,y:mode==='portrait'?62:68,w:mode==='portrait'?31:20,h:mode==='portrait'?6:7},
    left:{x:19,y:52,w:52,h:104},center:{x:50,y:52,w:mode==='portrait'?88:52,h:mode==='portrait'?102:104},right:{x:81,y:52,w:52,h:104},
    font:'sans',dialogueFrame:'',nameFrame:''
  });
  let studio=null,draft=null,activeId='',returnSelect=null,drag=null;
  function selectedMode(root){return root.querySelector('[name="vnpMode"]:checked')?.value||'landscape';}
  function injectSettings(root,record,config){
    const section=document.createElement('section');section.className='vnp-panel vnl-settings';section.innerHTML=`<div class="vnp-panel-head"><div><small>PAGE COMPOSITION</small><h3>自訂版面模板</h3></div></div><p>拖曳畫面中的人物、對話框與姓名框，儲存後可在其他篇章重用。選好模板後，請按底部「儲存頁面設置」套用；原版視覺小說不受影響。</p><div class="vnl-settings-row"><label class="vnp-field">套用版面<select id="vnpLayoutTemplate"></select></label><button type="button" class="btn btn-outline" id="vnlOpenStudio">設計版面 ↗</button></div>`;
    root.querySelector('.vnp-body')?.insertBefore(section,root.querySelector('.vnp-body')?.children[1]||null);
    const select=section.querySelector('select');
    const refresh=()=>{const mode=selectedMode(root),old=select.value||config.layoutTemplateId||'';select.innerHTML='<option value="">精選預設版面</option>'+templates().filter(row=>row.mode===mode).map(row=>`<option value="${esc(row.id)}">${esc(row.name)}</option>`).join('');select.value=[...select.options].some(option=>option.value===old)?old:'';};
    refresh();root.querySelectorAll('[name="vnpMode"]').forEach(input=>input.addEventListener('change',refresh));
    section.querySelector('#vnlOpenStudio').addEventListener('click',()=>open(selectedMode(root),select));
  }
  function open(mode,select){if(mode==='classic'){alert('請先選擇進階橫版或直版模板。');return;}returnSelect=select;activeId=select?.value||'';const existing=templates().find(row=>row.id===activeId&&row.mode===mode);draft={...defaults(mode),...(existing?.layout||{})};draft.dialogue={...defaults(mode).dialogue,...draft.dialogue};draft.name={...defaults(mode).name,...draft.name};for(const slot of ['left','center','right'])draft[slot]={...defaults(mode)[slot],...draft[slot]};
    studio=$('vnlStudio');if(!studio){studio=document.createElement('div');studio.id='vnlStudio';studio.className='vnl-backdrop';document.body.append(studio);}
    studio.dataset.mode=mode;renderStudio(existing?.name||`${mode==='portrait'?'直版':'橫版'}版面 ${templates().length+1}`);studio.classList.add('active');
  }
  const labels={dialogue:'對話框',name:'姓名框',left:'左側人物',center:'中央人物',right:'右側人物'};
  function renderStudio(name){
    const mode=studio.dataset.mode,portrait=mode==='portrait';
    studio.innerHTML=`<div class="vnl-shell" role="dialog" aria-modal="true" aria-label="版面設計"><header class="vnl-head"><div><small>VISUAL NOVEL · LAYOUT STUDIO</small><h2>設計${portrait?'直版':'橫版'}閱讀版面</h2><p>拖曳預覽中的區塊；數值會同步更新。舞台使用百分比定位，適應不同螢幕比例。</p></div><button type="button" data-vnl="close" aria-label="關閉">×</button></header><div class="vnl-main"><div class="vnl-preview-wrap"><div class="vnl-preview ${portrait?'portrait':'landscape'}" id="vnlPreview"><div class="vnl-preview-bg"></div>${(portrait?['center']:['left','center','right']).map(key=>`<div class="vnl-draggable vnl-character" data-drag="${key}"><span>${labels[key]}</span></div>`).join('')}<div class="vnl-draggable vnl-dialogue-preview" data-drag="dialogue"><span>對話框 · 對話文字顯示於此</span></div><div class="vnl-draggable vnl-name-preview" data-drag="name">人物姓名</div></div><p class="vnl-preview-hint">拖曳移動 · 在右側調整大小 · 儲存為可重用模板</p></div><div class="vnl-controls"><label class="vnl-field">模板名稱<input id="vnlName" maxlength="50" value="${esc(name)}"></label><label class="vnl-field">文字字體<select id="vnlFont"><option value="sans">黑體 · 清晰現代</option><option value="serif">明體 · 書卷質感</option></select></label><div class="vnl-control-grid">${(portrait?['center','dialogue','name']:['left','center','right','dialogue','name']).map(key=>`<fieldset><legend>${labels[key]}</legend>${['x','y','w','h'].map(axis=>`<label>${{x:'水平位置',y:'垂直位置',w:'寬度',h:'高度'}[axis]}<input type="number" data-key="${key}" data-axis="${axis}" min="0" max="120" step="1"></label>`).join('')}</fieldset>`).join('')}</div><div class="vnl-frame-controls"><h3>框體素材</h3><p>可用本機圖片或 HTTPS 圖片網址。透明 PNG／WebP 效果最佳。</p>${[['dialogueFrame','對話框'],['nameFrame','姓名框']].map(([key,label])=>`<label>${label}圖片網址<input type="url" data-frame-url="${key}" value="${esc(draft[key]||'')}" placeholder="https://…"></label><label class="vnl-upload">上傳${label}圖片<input type="file" accept="image/png,image/jpeg,image/webp,image/avif" data-frame-file="${key}"></label>`).join('')}</div><p id="vnlStatus" role="status"></p></div></div><footer class="vnl-footer"><button type="button" data-vnl="close">取消</button>${activeId?'<button type="button" data-vnl="delete" class="vnl-delete">刪除此模板</button>':''}<button type="button" data-vnl="duplicate">另存新模板</button><button type="button" data-vnl="save" class="vnl-primary">儲存並選取</button></footer></div>`;
    $('vnlFont').value=draft.font||'sans';
    studio.querySelectorAll('[data-key][data-axis]').forEach(input=>input.value=draft[input.dataset.key]?.[input.dataset.axis]??0);
    studio.onclick=onClick;studio.oninput=onInput;studio.onchange=onChange;studio.onpointerdown=onPointerDown;studio.onpointermove=onPointerMove;studio.onpointerup=onPointerUp;studio.onpointercancel=onPointerUp;
    paintPreview();
  }
  function paintPreview(){const stage=$('vnlPreview');if(!stage)return;stage.querySelectorAll('[data-drag]').forEach(el=>{const p=draft[el.dataset.drag];el.style.left=`${p.x}%`;el.style.top=`${p.y}%`;el.style.width=`${p.w}%`;el.style.height=`${p.h}%`;el.style.transform=el.dataset.drag==='left'||el.dataset.drag==='center'||el.dataset.drag==='right'?'translate(-50%,-50%)':'';});stage.style.fontFamily=draft.font==='serif'?'"Noto Serif TC", "Source Han Serif TC", serif':'Inter, "Noto Sans TC", sans-serif';for(const [key,selector] of [['dialogueFrame','[data-drag="dialogue"]'],['nameFrame','[data-drag="name"]']]){const target=stage.querySelector(selector),value=draft[key];if(!target||target.dataset.frameValue===value)continue;target.dataset.frameValue=value;if(!value){target.style.backgroundImage='';continue;}OCVnAssets.resolve(value).then(url=>{if(target.isConnected&&draft[key]===value)target.style.backgroundImage=`url("${String(url).replace(/["\\]/g,'')}")`;}).catch(()=>{});}}
  function onInput(event){const target=event.target;if(target.matches('[data-key][data-axis]')){draft[target.dataset.key][target.dataset.axis]=number(target.value,0,120);paintPreview();}if(target.id==='vnlFont'){draft.font=target.value;paintPreview();}if(target.matches('[data-frame-url]')){draft[target.dataset.frameUrl]=target.value.trim();paintPreview();}}
  async function onChange(event){const input=event.target;if(!input.matches('[data-frame-file]'))return;const file=input.files?.[0];if(!file)return;const status=$('vnlStatus');if(!/^image\/(png|jpeg|webp|avif)$/i.test(file.type)||file.size>20*1024*1024){status.textContent='請上傳小於 20 MB 的 PNG、JPEG、WebP 或 AVIF 圖片。';return;}const assetId=`vnl_frame_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;try{status.textContent='正在儲存框體圖片…';await OCFeatures.storeFile(assetId,file);mediaLibrary.push({id:assetId,kind:'vn-asset',assetType:'ui',listed:false,localOnly:true,title:file.name,type:file.type,size:file.size,createdAt:Date.now()});draft[input.dataset.frameFile]=`asset:${assetId}`;studio.querySelector(`[data-frame-url="${input.dataset.frameFile}"]`).value=draft[input.dataset.frameFile];saveStateToLocalStorage();paintPreview();status.textContent='框體圖片已儲存，儲存模板後即可套用。';}catch(error){status.textContent=`無法儲存圖片：${error.message}`;}}
  function onPointerDown(event){const el=event.target.closest?.('[data-drag]');if(!el||!$('vnlPreview')?.contains(el))return;const rect=$('vnlPreview').getBoundingClientRect(),key=el.dataset.drag;drag={key,pointer:event.pointerId,startX:event.clientX,startY:event.clientY,x:draft[key].x,y:draft[key].y,w:rect.width,h:rect.height};el.setPointerCapture(event.pointerId);event.preventDefault();}
  function onPointerMove(event){if(!drag||event.pointerId!==drag.pointer)return;const item=draft[drag.key];item.x=number(drag.x+(event.clientX-drag.startX)/drag.w*100,0,100);item.y=number(drag.y+(event.clientY-drag.startY)/drag.h*100,0,100);studio.querySelector(`[data-key="${drag.key}"][data-axis="x"]`).value=Math.round(item.x);studio.querySelector(`[data-key="${drag.key}"][data-axis="y"]`).value=Math.round(item.y);paintPreview();}
  function onPointerUp(event){if(drag?.pointer===event.pointerId)drag=null;}
  function onClick(event){const button=event.target.closest?.('[data-vnl]');if(!button)return;const action=button.dataset.vnl;if(action==='close')return close();if(action==='duplicate'){activeId='';$('vnlName').value=`${$('vnlName').value.trim()||'版面'} · 副本`;$('vnlStatus').textContent='已切換為另存新模板，按「儲存並套用」完成。';return;}if(action==='save')return save();if(action==='delete')return remove();}
  function save(){const name=$('vnlName').value.trim();if(!name){$('vnlStatus').textContent='請輸入模板名稱。';$('vnlName').focus();return;}for(const key of ['dialogueFrame','nameFrame']){const value=draft[key];if(value&&!/^https:\/\//i.test(value)&&!/^asset:[\w-]+$/.test(value)){$('vnlStatus').textContent='圖片網址請使用 HTTPS，或上傳本機圖片。';return;}}
    const id=activeId||`vnl_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`,row=templates().find(item=>item.id===id);if(row){row.name=name;row.layout=structuredClone(draft);row.updatedAt=Date.now();}else mediaLibrary.push({id,kind:'vn-layout-template',name,mode:studio.dataset.mode,layout:structuredClone(draft),createdAt:Date.now()});saveStateToLocalStorage();if(returnSelect){let option=[...returnSelect.options].find(item=>item.value===id);if(option)option.textContent=name;else{option=new Option(name,id);returnSelect.add(option);}returnSelect.value=id;}close();}
  function remove(){const row=templates().find(item=>item.id===activeId);if(!row)return;if(!confirm(`確定刪除版面模板「${row.name}」？已關聯的篇章會改用預設版面。`))return;const index=mediaLibrary.indexOf(row);mediaLibrary.splice(index,1);for(const record of [...(typeof books==='undefined'?[]:books),...(typeof documents==='undefined'?[]:documents)])if(record.visualNovelPage?.layoutTemplateId===row.id)record.visualNovelPage.layoutTemplateId='';saveStateToLocalStorage();if(returnSelect)returnSelect.value='';close();}
  function close(){studio?.classList.remove('active');studio?.replaceChildren();drag=null;}
  async function apply(player,config){if(!player||!config||config.mode==='classic')return;const row=templates().find(item=>item.id===config.layoutTemplateId&&item.mode===config.mode),layout=row?.layout||defaults(config.mode),dialogue=player.querySelector('.vnp-dialogue'),name=player.querySelector('.vnp-name');player.classList.add('vnl-designed');
    const d=layout.dialogue||defaults(config.mode).dialogue,n=layout.name||defaults(config.mode).name;
    dialogue.style.left=`${d.x}%`;dialogue.style.right='auto';dialogue.style.top=`${d.y}%`;dialogue.style.bottom='auto';dialogue.style.width=`${d.w}%`;dialogue.style.height=`${d.h}%`;dialogue.style.minHeight='0';
    name.style.left=`${(n.x-d.x)/d.w*100}%`;name.style.top=`${(n.y-d.y)/d.h*100}%`;name.style.width=`${n.w/d.w*100}%`;name.style.height=`${n.h/d.h*100}%`;name.style.maxWidth='none';
    player.style.fontFamily=layout.font==='serif'?'"Noto Serif TC", "Source Han Serif TC", serif':'Inter, "Noto Sans TC", sans-serif';
    for(const slot of ['left','center','right']){const p=layout[slot]||defaults(config.mode)[slot];player.style.setProperty(`--vnl-${slot}-x`,`${p.x}%`);player.style.setProperty(`--vnl-${slot}-w`,`${p.w}vw`);player.style.setProperty(`--vnl-${slot}-h`,`${p.h}vh`);player.style.setProperty(`--vnl-${slot}-bottom`,`${100-p.y-p.h/2}vh`);}
    for(const [key,target] of [['dialogueFrame',dialogue],['nameFrame',name]]){const value=layout[key];if(!value)continue;try{const url=await OCVnAssets.resolve(value);if(target?.isConnected&&url){target.style.setProperty('--vnl-frame',`url("${String(url).replace(/["\\]/g,'')}")`);target.classList.add('vnl-custom-frame');}}catch{}}
  }
  window.OCVnLayout={injectSettings,open,apply};
})();
