/* Shared visual-novel asset library. All management stays inside the page. */
(()=>{
  'use strict';
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const uid=prefix=>`${prefix}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`;
  const moods=['開心','悲傷','感動','浪漫','恐怖','憤怒','俏皮','寧靜','日常','神秘','嚴肅','緊張'];
  const baseExpressions=['普通','喜','怒','哀','樂','驚'];
  const folders=type=>mediaLibrary.filter(row=>row?.kind==='vn-folder'&&row.assetType===type);
  const assets=type=>mediaLibrary.filter(row=>row?.kind==='vn-asset'&&row.assetType===type&&row.listed!==false);
  const libraries=()=>mediaLibrary.filter(row=>row?.kind==='vn-sprite-library');
  const find=id=>mediaLibrary.find(row=>row.id===id);
  const save=()=>saveStateToLocalStorage();
  let overlay=null,tab='bg',folderId='',selectedId='',panel='',cropDrag=null;
  function open(type='bg',editId=''){tab=['cg','bg','bgm','se','sprite'].includes(type)?type:'bg';folderId='';selectedId=editId;panel=editId?'asset':'';if(!overlay){overlay=document.createElement('div');overlay.id='vnLibraryPage';overlay.className='vnl-backdrop';document.body.append(overlay);overlay.addEventListener('click',click);overlay.addEventListener('submit',submit);overlay.addEventListener('change',change);overlay.addEventListener('pointerdown',cropDown);overlay.addEventListener('pointermove',cropMove);overlay.addEventListener('pointerup',cropUp);}overlay.classList.add('active');render();}
  function close(){overlay?.classList.remove('active');overlay?.querySelectorAll('audio').forEach(audio=>audio.pause());panel='';window.OCVnPage?.refreshSettings?.();OCVnAssets.refresh?.();}
  function folderName(id){return folders(tab).find(row=>row.id===id)?.name||'未分類';}
  function imageType(type){return type==='bg'||type==='cg';}
  function icon(type){return imageType(type)?'fa-image':type==='bgm'||type==='se'?'fa-music':'fa-users-viewfinder';}
  function render(){if(!overlay)return;const group=folders(tab),rows=tab==='sprite'?libraries():assets(tab).filter(row=>!folderId||row.folderId===folderId),title={cg:'CG 圖片',bg:'背景場景',bgm:'BGM 音樂',se:'SE 音效',sprite:'人物立繪'}[tab];overlay.innerHTML=`<main class="vnl-shell" role="dialog" aria-modal="true" aria-label="視覺小說素材庫"><header class="vnl-head"><div><small>STORY STUDIO / ASSET ARCHIVE</small><h2>視覺小說素材庫</h2><p>整理 CG、背景、音樂、音效與立繪；編輯器直接共用這些素材。</p></div><button class="vnl-close" data-act="close" aria-label="關閉素材庫">×</button></header><div class="vnl-tabs">${[['cg','CG 圖片'],['bg','背景場景'],['bgm','BGM 音樂'],['se','SE 音效'],['sprite','人物立繪']].map(([type,label])=>`<button data-act="tab" data-type="${type}" class="${tab===type?'active':''}"><i class="fa-solid ${icon(type)}"></i> ${label}</button>`).join('')}</div><div class="vnl-layout"><aside class="vnl-sidebar"><div class="vnl-side-title"><span>${tab==='sprite'?'立繪素材庫':'資料夾'}</span><button data-act="new-${tab==='sprite'?'library':'folder'}" aria-label="新增">＋</button></div>${tab==='sprite'?`<p class="vnl-hint">每本書或每篇文檔可以關聯不同的立繪庫。</p>`:`<button class="vnl-folder ${!folderId?'active':''}" data-act="folder" data-id=""><i class="fa-solid fa-layer-group"></i> 全部素材 <b>${assets(tab).length}</b></button>${group.map(row=>`<div class="vnl-folder-row"><button class="vnl-folder ${folderId===row.id?'active':''}" data-act="folder" data-id="${esc(row.id)}"><i class="fa-solid fa-folder"></i> <span>${esc(row.name)}</span><b>${assets(tab).filter(item=>item.folderId===row.id).length}</b></button><button class="vnl-mini" data-act="edit-folder" data-id="${esc(row.id)}" title="編輯資料夾">⋯</button></div>`).join('')}`}</aside><section class="vnl-content"><div class="vnl-content-head"><div><small>${esc(folderId?folderName(folderId):'ALL ASSETS')}</small><h3>${title}</h3></div><button class="vnl-primary" data-act="new-${tab==='sprite'?'library':'asset'}">＋ 新增${tab==='sprite'?'立繪庫':'素材'}</button></div><div class="vnl-grid">${rows.map(row=>tab==='sprite'?libraryCard(row):assetCard(row)).join('')||`<div class="vnl-empty"><i class="fa-solid ${icon(tab)}"></i><h3>還沒有${title}</h3><p>按右上角新增，素材可用網址或本機檔案建立。</p></div>`}</div></section></div>${panel?renderPanel():''}</main>`;hydratePreviews();if(panel==='asset')hydrateAssetEditor();if(panel==='cast')hydrateCastEditor();}
  function assetCard(row){return `<article class="vnl-card"><div class="vnl-card-media" data-preview="${esc(row.id)}">${imageType(tab)?'<i class="fa-solid fa-image"></i>':'<i class="fa-solid fa-music"></i>'}</div><div class="vnl-card-body"><small>${esc(folderName(row.folderId))}</small><h4>${esc(row.title||'未命名')}</h4>${(row.tags||[]).length?`<p>${esc(row.tags.join(' · '))}</p>`:''}<button data-act="edit-asset" data-id="${esc(row.id)}">編輯素材 <span>↗</span></button></div></article>`;}
  function libraryCard(row){return `<article class="vnl-card vnl-library-card"><div class="vnl-card-media"><i class="fa-solid fa-masks-theater"></i></div><div class="vnl-card-body"><small>${Object.keys(row.cast||{}).length} 位人物</small><h4>${esc(row.name)}</h4><button data-act="edit-library" data-id="${esc(row.id)}">管理人物與立繪 <span>↗</span></button></div></article>`;}
  function renderPanel(){const row=find(selectedId);if(panel==='folder')return `<div class="vnl-panel-mask"><section class="vnl-panel"><header><small>ORGANIZE</small><h3>${row?'編輯資料夾':'新增資料夾'}</h3><button data-act="dismiss">×</button></header><form data-form="folder"><label>資料夾名稱<input name="name" required maxlength="80" value="${esc(row?.name||'')}" placeholder="例如：校園、家庭、夜景"></label><footer>${row?`<button type="button" class="vnl-danger" data-act="delete-folder" data-id="${esc(row.id)}">刪除資料夾</button>`:''}<button class="vnl-primary">儲存資料夾</button></footer></form></section></div>`;
    if(panel==='asset')return `<div class="vnl-panel-mask"><section class="vnl-panel"><header><small>${tab==='bg'?'SCENE ASSET':'AUDIO ASSET'}</small><h3>${row?'編輯素材':'新增素材'}</h3><button data-act="dismiss">×</button></header><form data-form="asset"><label>素材名稱<input name="title" required maxlength="120" value="${esc(row?.title||'')}" placeholder="${tab==='bg'?'例如：校園-教室':'例如：安靜的午後'}"></label><label>存放資料夾<select name="folderId"><option value="">未分類</option>${folders(tab).map(folder=>`<option value="${esc(folder.id)}" ${(row?.folderId||folderId)===folder.id?'selected':''}>${esc(folder.name)}</option>`).join('')}</select></label><label>素材網址<input name="url" type="url" value="${esc(row?.url||'')}" placeholder="https://…"></label><label>或選擇本機${tab==='bg'?'圖片':'音樂'}<input name="file" type="file" accept="${tab==='bg'?'image/*':'audio/*'}"></label>${tab==='bgm'?`<label>情緒標籤<input name="tags" value="${esc((row?.tags||[]).join('、'))}" placeholder="例如：${moods.slice(0,4).join('、')}"></label><div class="vnl-moods">${moods.map(tag=>`<button type="button" data-act="mood" data-tag="${tag}">${tag}</button>`).join('')}</div>`:''}${tab==='bg'?`<div class="vnl-crop-section"><strong>直版背景顯示範圍</strong><p>在圖片上拖曳選取直版要聚焦的區域；橫版仍顯示完整背景。</p><div class="vnl-crop-board vnl-scene-board" data-crop="scene"><img alt="背景裁切預覽"><span class="vnl-crop-box"></span></div><button type="button" data-act="reset-crop">重設顯示範圍</button></div>`:''}<div class="vnl-form-preview" id="vnlFormPreview"></div><footer>${row?`<button type="button" class="vnl-danger" data-act="delete-asset" data-id="${esc(row.id)}">刪除素材</button>`:''}<button class="vnl-primary">儲存素材</button></footer></form></section></div>`;
    if(panel==='library')return `<div class="vnl-panel-mask"><section class="vnl-panel"><header><small>CAST ARCHIVE</small><h3>${row?'管理立繪庫':'新增立繪庫'}</h3><button data-act="dismiss">×</button></header><form data-form="library"><label>立繪庫名稱<input name="name" required maxlength="100" value="${esc(row?.name||'')}" placeholder="例如：校園篇立繪"></label><label class="vnl-inline"><input name="allCharacters" type="checkbox" ${row?.allCharacters?'checked':''}> 關聯全部人物</label><footer>${row?`<button type="button" class="vnl-danger" data-act="delete-library" data-id="${esc(row.id)}">刪除立繪庫</button>`:''}<button class="vnl-primary">儲存</button></footer></form>${row?`<div class="vnl-cast-list"><h4>關聯人物</h4><div class="vnl-add-cast"><select id="vnlNewChar"><option value="">選擇人物</option>${OCRecordPolicy.characters().filter(char=>!row.cast?.[char.id]).map(char=>`<option value="${esc(char.id)}">${esc(char.name)}</option>`).join('')}</select><button data-act="add-cast">加入</button></div>${Object.keys(row.cast||{}).filter(id=>OCRecordPolicy.character(id)).map(charId=>`<button data-act="edit-cast" data-id="${esc(charId)}"><span>${esc(OCRecordPolicy.characters().find(char=>String(char.id)===String(charId))?.name||charId)}</span><span>編輯表情與裁切 →</span></button>`).join('')}</div>`:''}</section></div>`;
    if(panel==='cast'){const library=libraries().find(item=>item.id===selectedId),charId=overlay.dataset.charId,entry=library?.cast?.[charId],char=OCRecordPolicy.characters().find(item=>String(item.id)===String(charId));return `<div class="vnl-panel-mask"><section class="vnl-panel"><header><small>${esc(library?.name||'')}</small><h3>${esc(char?.name||'人物')} · 立繪與表情</h3><button data-act="back-library">←</button></header><p class="vnl-hint">普通表情未設定時使用人物檔案頭像。裁切框適用所有表情。</p><label class="vnl-inline"><input type="checkbox" data-avatar-mode ${entry?.avatarMode?'checked':''}> 預設顯示為頭像模式</label><div class="vnl-crop-section"><strong>圖形化頭像裁切</strong><div class="vnl-crop-board" data-crop="avatar"><img alt="立繪裁切預覽"><span class="vnl-crop-box"></span></div><small>拖曳圖片上的方框範圍</small></div><div class="vnl-expression-list">${[...new Set([...baseExpressions,...Object.keys(entry?.images||{})])].map(name=>`<form data-form="expression" data-expression="${esc(name)}"><label>${esc(name)}<input name="url" type="url" value="${esc(entry?.images?.[name]?.startsWith('asset:')?'':entry?.images?.[name]||'')}" placeholder="https:// 圖片網址"></label><input name="file" type="file" accept="image/*"><button>儲存</button>${!baseExpressions.includes(name)?`<button type="button" data-act="delete-expression" data-name="${esc(name)}">刪除</button>`:''}</form>`).join('')}</div><form data-form="new-expression" class="vnl-add-cast"><input name="name" required maxlength="40" placeholder="自訂表情名稱"><button>＋ 加入表情</button></form><footer><button class="vnl-danger" data-act="remove-cast">移除這位人物</button></footer></section></div>`;}
    return '';
  }
  async function hydratePreviews(){for(const box of overlay.querySelectorAll('[data-preview]')){const row=find(box.dataset.preview);if(!row)continue;try{const url=await OCVnAssets.resolve(row.url||`asset:${row.id}`);if(!box.isConnected)return;if(imageType(tab))box.innerHTML=`<img src="${esc(url)}" alt="${esc(row.title)}" loading="lazy">`;else box.innerHTML=`<audio controls preload="none" src="${esc(url)}"></audio>`;}catch{box.textContent='預覽暫不可用';}}}
  async function hydrateAssetEditor(){const row=find(selectedId),preview=$('vnlFormPreview'),board=overlay.querySelector('[data-crop="scene"]'),form=overlay.querySelector('[data-form="asset"]');if(form){const file=form.querySelector('[name="file"]');if(file){file.accept=imageType(tab)?'image/*':'audio/*';file.parentElement.firstChild.textContent=`或選擇本機${imageType(tab)?'圖片':'音訊'}`;}if(tab!=='bgm'){const mood=form.querySelector('.vnl-moods');mood?.remove();if(!form.querySelector('[name="tags"]')){const label=document.createElement('label');label.textContent='素材標籤';label.innerHTML+=`<input name="tags" value="${esc((row?.tags||[]).join('、'))}" placeholder="用頓號分隔標籤">`;file?.parentElement.after(label);}}}if(!row)return;try{const url=await OCVnAssets.resolve(row.url||`asset:${row.id}`);if(preview?.isConnected)preview.innerHTML=imageType(tab)?`<img src="${esc(url)}" alt="素材預覽">`:`<audio controls src="${esc(url)}"></audio>`;if(board?.isConnected){const image=board.querySelector('img');image.onload=()=>fitCropBoard(board,image);image.src=url;paintCrop(board,row.portraitFrame||{x:25,y:0,w:50,h:100});}}catch{if(preview)preview.textContent='預覽暫不可用';}}
  async function hydrateCastEditor(){const board=overlay.querySelector('[data-crop="avatar"]'),library=find(selectedId),entry=library?.cast?.[overlay.dataset.charId],char=OCRecordPolicy.characters().find(item=>String(item.id)===String(overlay.dataset.charId));if(!board||!entry)return;paintCrop(board,entry.crop||{x:25,y:0,w:50,h:50});overlay.querySelectorAll('[data-form="expression"]').forEach(form=>{const name=form.dataset.expression;if(!entry.images?.[name]||form.querySelector('.vnl-clear-image'))return;const button=document.createElement('button');button.type='button';button.className='vnl-clear-image';button.textContent='移除此圖';button.addEventListener('click',()=>clearCastImage(name));form.append(button);});try{const value=entry.images?.['普通']||char?.avatar||char?.image||'';if(value){const image=board.querySelector('img');image.onload=()=>fitCropBoard(board,image);image.src=await OCVnAssets.resolve(value);}}catch{}}
  function fitCropBoard(board,image){if(!image.naturalWidth||!image.naturalHeight)return;const maxWidth=Math.min(430,board.parentElement.clientWidth-20),maxHeight=320,scale=Math.min(maxWidth/image.naturalWidth,maxHeight/image.naturalHeight);board.style.width=`${Math.round(image.naturalWidth*scale)}px`;board.style.height=`${Math.round(image.naturalHeight*scale)}px`;}
  function paintCrop(board,crop){const box=board.querySelector('.vnl-crop-box');if(!box)return;for(const [key,value] of Object.entries({left:crop.x,top:crop.y,width:crop.w,height:crop.h}))box.style[key]=`${value}%`;}
  function pos(board,event){const rect=board.getBoundingClientRect();return {x:Math.max(0,Math.min(100,(event.clientX-rect.left)/rect.width*100)),y:Math.max(0,Math.min(100,(event.clientY-rect.top)/rect.height*100))};}
  function cropDown(event){const board=event.target.closest?.('[data-crop]');if(!board||!overlay.contains(board))return;cropDrag={board,start:pos(board,event)};board.setPointerCapture?.(event.pointerId);event.preventDefault();}
  function cropMove(event){if(!cropDrag)return;const {board,start}=cropDrag,end=pos(board,event);paintCrop(board,{x:Math.min(start.x,end.x),y:Math.min(start.y,end.y),w:Math.abs(start.x-end.x),h:Math.abs(start.y-end.y)});}
  function cropUp(event){if(!cropDrag)return;const {board,start}=cropDrag,end=pos(board,event);cropDrag=null;const crop={x:Math.round(Math.min(start.x,end.x)),y:Math.round(Math.min(start.y,end.y)),w:Math.max(2,Math.round(Math.abs(start.x-end.x))),h:Math.max(2,Math.round(Math.abs(start.y-end.y)))};paintCrop(board,crop);if(board.dataset.crop==='scene'){board.dataset.frame=JSON.stringify(crop);}else{const entry=find(selectedId)?.cast?.[overlay.dataset.charId];if(entry){entry.crop=crop;save();}}}
  function click(event){
    const button=event.target.closest('[data-act]');if(!button)return;const act=button.dataset.act;
    if(act==='close')return close();
    if(act==='dismiss'){panel='';return render();}
    if(act==='tab'){tab=button.dataset.type;folderId='';selectedId='';panel='';return render();}
    if(act==='folder'){folderId=button.dataset.id||'';return render();}
    if(act==='new-folder'||act==='edit-folder'){selectedId=button.dataset.id||'';panel='folder';return render();}
    if(act==='new-asset'||act==='edit-asset'){selectedId=button.dataset.id||'';panel='asset';return render();}
    if(act==='new-library'||act==='edit-library'){selectedId=button.dataset.id||'';panel='library';return render();}
    if(act==='back-library'){panel='library';return render();}
    if(act==='edit-cast'){overlay.dataset.charId=button.dataset.id;panel='cast';return render();}
    if(act==='add-cast'){const row=find(selectedId),charId=$('vnlNewChar')?.value;if(!row||!charId)return;row.cast=row.cast||{};row.cast[charId]={images:{},crop:{x:25,y:0,w:50,h:50},avatarMode:false};save();return render();}
    if(act==='mood'){const input=overlay.querySelector('[name="tags"]'),set=new Set((input.value||'').split(/[,，、]/).map(s=>s.trim()).filter(Boolean));set.add(button.dataset.tag);input.value=[...set].join('、');return;}
    if(act==='reset-crop'){const board=overlay.querySelector('[data-crop="scene"]');if(board){const frame={x:25,y:0,w:50,h:100};board.dataset.frame=JSON.stringify(frame);paintCrop(board,frame);}return;}
    if(act==='delete-folder')return deleteFolder(button.dataset.id);
    if(act==='delete-asset')return deleteAsset(button.dataset.id);
    if(act==='delete-library')return deleteLibrary(button.dataset.id);
    if(act==='remove-cast')return removeCast();
    if(act==='delete-expression')return deleteExpression(button.dataset.name);
  }
  async function submit(event){
    const form=event.target.closest('[data-form]');if(!form||!overlay.contains(form))return;
    event.preventDefault();const kind=form.dataset.form,data=new FormData(form),name=String(data.get('name')||'').trim();
    if(kind==='folder'){if(!name)return;const row=find(selectedId);if(row)row.name=name;else mediaLibrary.push({id:uid('vnf'),kind:'vn-folder',assetType:tab,name});save();panel='';return render();}
    if(kind==='library'){if(!name)return;let row=find(selectedId);if(!row){row={id:uid('vns'),kind:'vn-sprite-library',name,cast:{},allCharacters:false};mediaLibrary.push(row);selectedId=row.id;}row.name=name;row.allCharacters=!!data.get('allCharacters');save();return render();}
    if(kind==='asset'){
      const title=String(data.get('title')||'').trim(),url=String(data.get('url')||'').trim(),file=data.get('file');if(!title)return;
      let row=find(selectedId);if(!row&&!url&&(!file||!file.size))return alert('請選擇檔案或填入網址。');
      if(url&&!url.toLowerCase().startsWith('https://'))return alert('素材網址請使用 HTTPS。');
      if(file?.size){const limit=imageType(tab)?20:50;if(file.size>limit*1024*1024)return alert(`檔案不可超過 ${limit} MB。`);if(!(imageType(tab)?file.type.startsWith('image/'):file.type.startsWith('audio/')))return alert('請選擇正確的圖片或音訊格式。');}
      const id=row?.id||uid('vna');try{
        if(file?.size)await OCFeatures.storeFile(id,file);
        if(!row){row={id,kind:'vn-asset',assetType:tab,listed:true,createdAt:Date.now()};mediaLibrary.push(row);}
        row.title=title;row.folderId=String(data.get('folderId')||'');row.tags=String(data.get('tags')||'').split(/[,，、]/).map(s=>s.trim()).filter(Boolean);
        if(file?.size){row.type=file.type;row.size=file.size;row.localOnly=true;delete row.url;}else if(url){row.url=url;row.localOnly=false;}
        const frame=overlay.querySelector('[data-crop="scene"]')?.dataset.frame;if(tab==='bg'&&frame)row.portraitFrame=JSON.parse(frame);
        save();panel='';render();OCVnAssets.render();
      }catch(error){alert(`素材儲存失敗：${error.message}`);}return;
    }
    if(kind==='new-expression'){const row=find(selectedId),entry=row?.cast?.[overlay.dataset.charId];if(!name||!entry)return;entry.images=entry.images||{};if(!(name in entry.images))entry.images[name]='';save();render();return hydrateCastEditor();}
    if(kind==='expression'){
      const row=find(selectedId),entry=row?.cast?.[overlay.dataset.charId],mood=form.dataset.expression,url=String(data.get('url')||'').trim(),file=data.get('file');if(!entry)return;
      if(!url&&!file?.size)return;
      if(url&&!url.toLowerCase().startsWith('https://'))return alert('請使用 HTTPS 圖片網址。');
      try{if(file?.size){if(!file.type.startsWith('image/')||file.size>20*1024*1024)return alert('請選擇 20 MB 以下圖片。');const assetId=uid('vna');await OCFeatures.storeFile(assetId,file);mediaLibrary.push({id:assetId,kind:'vn-asset',assetType:'sprite',title:`${OCRecordPolicy.characters().find(char=>String(char.id)===String(overlay.dataset.charId))?.name||'人物'}-${mood}`,type:file.type,size:file.size,localOnly:true,listed:false,createdAt:Date.now()});entry.images[mood]=`asset:${assetId}`;}else entry.images[mood]=url;save();render();return hydrateCastEditor();}catch(error){alert(`儲存表情失敗：${error.message}`);}
    }
  }
  function change(event){if(event.target.matches('[data-avatar-mode]')){const entry=find(selectedId)?.cast?.[overlay.dataset.charId];if(entry){entry.avatarMode=event.target.checked;save();}}const input=event.target;if(input.name==='file'&&input.files?.[0]){const url=URL.createObjectURL(input.files[0]),preview=$('vnlFormPreview');if(preview)preview.innerHTML=imageType(tab)?`<img src="${url}" alt="新素材預覽">`:`<audio controls src="${url}"></audio>`;const board=overlay.querySelector('[data-crop="scene"]');if(board){const image=board.querySelector('img');image.onload=()=>fitCropBoard(board,image);image.src=url;}}if(input.name==='url'&&panel==='asset'&&input.value.toLowerCase().startsWith('https://')){const preview=$('vnlFormPreview');if(preview)preview.innerHTML=imageType(tab)?`<img src="${esc(input.value)}" alt="網址素材預覽">`:`<audio controls src="${esc(input.value)}"></audio>`;const board=overlay.querySelector('[data-crop="scene"]');if(board){const image=board.querySelector('img');image.onload=()=>fitCropBoard(board,image);image.src=input.value;}}}
  function usageCount(assetId){const token=`asset:${assetId}`;let count=0;for(const record of [...books,...documents]){const cfg=record.visualNovelPage||{};if([...(cfg.sceneAssetIds||[]),...(cfg.musicAssetIds||[])].includes(assetId))count++;if(JSON.stringify(record.visualNovel||{}).includes(token))count++;}for(const library of libraries())for(const entry of Object.values(library.cast||{}))if(Object.values(entry.images||{}).includes(token))count++;return count;}
  async function deleteAsset(id){const row=find(id);if(!row)return;const uses=usageCount(id);if(uses)return alert(`此素材仍被 ${uses} 處書籍、文檔或人物立繪使用。請先解除關聯，再刪除素材。`);if(!confirm(`確定刪除「${row.title||'未命名'}」？此操作無法復原。`))return;try{if(row.localOnly)await OCFeatures.removeFile(id);else if(!row.url)await OCFeatures.deleteRemoteFile(id);mediaLibrary=mediaLibrary.filter(item=>item.id!==id);save();panel='';render();}catch(error){alert(`刪除失敗：${error.message}`);}}
  function deleteFolder(id){const row=find(id);if(!row||!confirm(`刪除資料夾「${row.name}」？裡面的素材會移到「未分類」，不會被刪除。`))return;assets(tab).filter(item=>item.folderId===id).forEach(item=>item.folderId='');mediaLibrary=mediaLibrary.filter(item=>item.id!==id);folderId='';panel='';save();render();}
  function deleteLibrary(id){const row=find(id);if(!row)return;const linked=[...books,...documents].filter(record=>record.visualNovelPage?.spriteLibraryId===id);if(linked.length)return alert(`這個立繪庫仍與 ${linked.length} 本書／篇文檔關聯。請先解除關聯。`);if(!confirm(`確定刪除立繪庫「${row.name}」？獨立圖片素材不會自動刪除。`))return;mediaLibrary=mediaLibrary.filter(item=>item.id!==id);panel='';save();render();}
  function removeCast(){const row=find(selectedId),charId=overlay.dataset.charId;if(!row?.cast?.[charId])return;if(!confirm('從這個立繪庫移除此人物？人物檔案本身不會刪除。'))return;delete row.cast[charId];panel='library';save();render();}
  async function clearCastImage(name){const entry=find(selectedId)?.cast?.[overlay.dataset.charId],value=entry?.images?.[name];if(!value||!confirm(`移除「${name}」的立繪圖片？`))return;const assetId=value.startsWith('asset:')?value.slice(6):'',row=find(assetId);try{if(row&&usageCount(assetId)<=1){if(row.localOnly)await OCFeatures.removeFile(assetId);else if(!row.url)await OCFeatures.deleteRemoteFile(assetId);mediaLibrary=mediaLibrary.filter(item=>item.id!==assetId);}entry.images[name]='';save();render();hydrateCastEditor();}catch(error){alert(`移除圖片失敗：${error.message}`);}}
  async function deleteExpression(name){const entry=find(selectedId)?.cast?.[overlay.dataset.charId];if(!entry||baseExpressions.includes(name))return;if(!confirm(`刪除「${name}」表情？`))return;const value=entry.images[name]||'',assetId=value.startsWith('asset:')?value.slice(6):'',row=find(assetId);try{if(row&&usageCount(assetId)<=1){if(row.localOnly)await OCFeatures.removeFile(assetId);else if(!row.url)await OCFeatures.deleteRemoteFile(assetId);mediaLibrary=mediaLibrary.filter(item=>item.id!==assetId);}delete entry.images[name];save();render();}catch(error){alert(`刪除表情失敗：${error.message}`);}}
  window.OCVnLibrary={open,close,refresh:()=>overlay?.classList.contains('active')&&render()};
})();
